Repository stashapp/CommunityScrapers, pull requests merged in 2020-06, with the labels that each got.

#70 Adds SexVR xPath scraper
  README.md
  SCENE-SCRAPABLE.md
  scrapers/SexVR.yml
Labels: xPath

#69 Add Performer Scraping support to ManyVids
  README.md
  scrapers/ManyVids.yml
Labels: xPath

#74 Add FuckingAwesome xPath scene scraper
  SCENE-SCRAPABLE.md
  scrapers/FuckingAwesome.yml
Labels: xPath

#78 Fix image scraping in BangBros scraper
  scrapers/BangBros.yml
Labels: fix

#77 Adds AngelaWhite xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/AngelaWhite.yml
Labels: xPath

#79 Fix image scraping in NaughtyAmerica xpath scraper
  scrapers/NaughtyAmerica.yml
Labels: fix

#91 Add Puffynetwork and Vipissy xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/Puffynetwork.yml
  scrapers/Vipissy.yml
Labels: xPath

#83 Adds XXXPawn xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/XXXPawn.yml
Labels: xPath

#89 Add studio field to GammaEntertainment
  SCENE-SCRAPABLE.md
  scrapers/GammaEntertainment.yml
  scrapers/Vivid.yml
Labels: enhancement

#84 Adds iKissGirls xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/IKissGirls.yml
Labels: xPath

#54 Adds IsThisReal xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/IsThisReal.yml
Labels: xPath

#95 Adds Fistertwister xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/Fistertwister.yml
Labels: xPath

#96 Adds Firstanalquest xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/Firstanalquest.yml
Labels: xPath

#90 Add Teencoreclub xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/Teencoreclub.yml
Labels: xPath

#97 Add tags to xxxpawn
  scrapers/XXXPawn.yml
Labels: enhancement

#98 Update PaperStreetMedia
  SCENE-SCRAPABLE.md
  scrapers/PaperStreetMedia.yml
Labels: enhancement

#94 Adds joymii xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/joymii.yml
Labels: xPath

#85 Adds FamilyTherapyXXX xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/FamilyTherapyXXX.yml
Labels: xPath

#99 Adds xtube xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/Xtube.yml
Labels: xPath

#102 fixed kink.com
  scrapers/Kink.yml
Labels: fix

#100 Adds Xvideos and Xnxx xPath scrapers
  SCENE-SCRAPABLE.md
  scrapers/Xnxx.yml
  scrapers/Xvideos.yml
Labels: xPath
