Repository stashapp/CommunityScrapers, pull requests merged in 2020-12, with the labels that each got.

#297 support cookies in scraper schema
  validator/index.js
  validator/scraper.schema.json
Labels: enhancement

#266 Add Colette xPath scene, gallery scraper
  SCRAPERS-LIST.md
  scrapers/Colette.yml
Labels: xPath

#298 Purgatoryx scraper (Xpath)
  SCRAPERS-LIST.md
  scrapers/purgatoryx.yml
Labels: xPath

#296 Add StudioFOW xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/StudioFOW.yml
Labels: xPath

#300 Add girlgrind to MindGeek
  SCRAPERS-LIST.md
  scrapers/MindGeek.yml
Labels: enhancement

#301 Mgstage Scraper (Xpath + Cookie 🍪)
  SCRAPERS-LIST.md
  scrapers/mgstage.yml
Labels: xPath

#299 Update KellyMadisonMedia.yml (Cookie Update)
  SCRAPERS-LIST.md
  scrapers/KellyMadisonMedia.yml
Labels: enhancement, fix

#302 TeenMegaWorld XPath scene scraper
  SCRAPERS-LIST.md
  scrapers/TeenMegaWorld.yml
Labels: xPath

#304 JavDB Scraper (Xpath + Json + Cookie)
  SCRAPERS-LIST.md
  scrapers/javdb.yml
Labels: JSON, xPath

#306 remove infernalrestraints.yml. remove sexuallybroken.com. add insex.yml
  SCRAPERS-LIST.md
  scrapers/infernalrestraints.yml
  scrapers/insex.yml
Labels: fix

#311 Update GirlsOutWest.yml
  SCRAPERS-LIST.md
  scrapers/GirlsOutWest.yml
Labels: enhancement

#305 Penthouse Scraper (Xpath)
  SCRAPERS-LIST.md
  scrapers/Penthouse.yml
Labels: xPath

#312 Add aziani and gloryholesecrets to gangbangcreampie xPath Scraper
  SCRAPERS-LIST.md
  scrapers/GangBangCreampie.yml
Labels: xPath

#310 Fix TrafficPimps Scraper
  SCRAPERS-LIST.md
  scrapers/trafficpimps.yml
Labels: fix

#314 Hegre: Add `/massage`
  scrapers/Hegre.yml
Labels: enhancement

#318 Enable merge key support in validator
  SCRAPERS-LIST.md
  validator/index.js
Labels: enhancement

#317 Straplezz Scraper (Xpath)
  SCRAPERS-LIST.md
  scrapers/Straplezz.yml
Labels: xPath

#315 Add fetishnetwork xPath scraper
  SCRAPERS-LIST.md
  scrapers/FetishNetwork.yml
Labels: xPath

#316 Update RawAttack.yml
  scrapers/RawAttack.yml
Labels: fix

#319 added gallery scraping support for Brazzers.yml
  scrapers/Brazzers.yml
Labels: xPath

#322 Update R18 (sceneByFragment + censor)
  scrapers/r18.yml
Labels: enhancement

#326 Update DorcelClub.yml
  scrapers/DorcelClub.yml
Labels: fix

#323 Added 1Pondo xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/1pondo.yml
Labels: CDP, xPath

#307 added czechcasting.com
  scrapers/czechcasting.yml
Labels: xPath

#328 Added PerformerByURL scraper, feminized.com to FemdomEmpire
  SCRAPERS-LIST.md
  scrapers/FemDomEmpire.yml
  scrapers/FemdomEmpire.yml
Labels: enhancement

#324 Update javlibrary.yml (Subscraper R18)
  scrapers/javlibrary.yml
Labels: enhancement
