Repository stashapp/CommunityScrapers, pull requests merged in 2020-08, with the labels that each got.

#112 Adding several new scrapers
  SCENE-SCRAPABLE.md
  scrapers/AnalizedNetwork.yml
  scrapers/ArchAngelVideo.yml
  scrapers/DogFart.yml
  scrapers/JaysPov.yml
  scrapers/Karups.yml
  scrapers/Nubiles.yml
  scrapers/PaperStreetMedia.yml
  scrapers/ProducersFun.yml
  scrapers/RealityKings.yml
Labels: xPath

#1 Create vixenNetwork.yml
  vixenNetwork.yml
Labels: xPath

#117 Add PureTaboo, Bang.com xPath scene scrapers
  SCENE-SCRAPABLE.md
  scrapers/Bang.yml
  scrapers/PureTaboo.yml
Labels: CDP, xPath

#124 Babepedia fixes
  scrapers/Babepedia.yml
Labels: fix

#120 Post process refactor
  scrapers/Firstanalquest.yml
  scrapers/Fistertwister.yml
  scrapers/Puffynetwork.yml
  scrapers/Vipissy.yml
  scrapers/Xnxx.yml
  scrapers/Xtube.yml
  scrapers/Xvideos.yml
Labels: fix

#126 Edit xPath (Mostly image)
  scrapers/Bang.yml
  scrapers/BangBros.yml
  scrapers/Brazzers.yml
  scrapers/Mypervyfamily.yml
  scrapers/PureTaboo.yml
  scrapers/Spizoo.yml
Labels: enhancement

#131 Add DorcelClub xPath scene scraper
  SCENE-SCRAPABLE.md
  scrapers/DorcelClub.yml
Labels: xPath

#121 Add performerByURL and movieByURL scrapers to Gamma Entertainment and Jules Jordan
  scrapers/GammaEntertainment.yml
  scrapers/JulesJordan.yml
Labels: enhancement

#132 Add movie scraping to AEBN
  scrapers/AEBN.yml
Labels: enhancement

#141 Adding XsList Performer Scraper (JAV)
  README.md
  scrapers/Xslist.yml
Labels: xPath

#118 Improve LegalPorno. Add AssTraffic.
  scrapers/AssTraffic.yml
  scrapers/LegalPorno.py
  scrapers/LegalPorno.yml
Labels: script, xPath

#130 Add ThePornDB (metadataapi.net) JSON scraper
  README.md
  SCENE-SCRAPABLE.md
  scrapers/ThePornDB.yml
Labels: JSON

#125 PornDB xPath Scraper (metadataapi)
  SCENE-SCRAPABLE.md
  scrapers/PornDB.yml
Labels: xPath

#119 Adding GirsOutWest scraper
  SCENE-SCRAPABLE.md
  scrapers/GirlsOutWest.yml
Labels: xPath

#135 Adding ChristianXXX TS sites
  SCENE-SCRAPABLE.md
  scrapers/ChristianXXX.yml
Labels: xPath

#109 Add Modelhub scraper
  scrapers/Modelhub.yml
Labels: xPath

#146 Add TimTales scraper
  SCENE-SCRAPABLE.md
  scrapers/TimTales.yml
Labels: xPath

#139 Add HimerosTV & TimTales xPath scene scraper
  SCENE-SCRAPABLE.md
  scrapers/HimerosTV.yml
  scrapers/TimTales.yml
Labels: xPath

#147 Add GangBangCreampie xPath scene scraper
  SCENE-SCRAPABLE.md
  scrapers/GangBangCreampie.yml
Labels: xPath

#129 Add a couple of movie scrapers.
  scrapers/AdultDvdMarketPlace.yml
  scrapers/AdultEmpire.yml
  scrapers/Iafd.yml
  scrapers/IafdStreaming.yml
Labels: xPath

#122 RealityKings: Update to match site again.
  scrapers/RealityKings.yml
Labels: fix
