Repository stashapp/CommunityScrapers, pull requests merged in 2020-11, with the labels that each got.

#250 Fix invalid scrapers
  scrapers/FrolicMe.yml
  scrapers/Mypervmom.yml
  scrapers/VNAGirls.yml
Labels: fix

#252 adjust vixen cover selector
  scrapers/vixenNetwork.yml
Labels: enhancement

#236 adding scraper for AussieAss.com aussiepov.com
  SCENE-SCRAPABLE.md
  scrapers/AussieAss.yml
Labels: xPath

#251 add MFC Share scraper
  SCENE-SCRAPABLE.md
  scrapers/MFC.yml
Labels: xPath

#257 Add brandibelle xPath scene scrapper
  SCENE-SCRAPABLE.md
  scrapers/brandibelle.yml
Labels: xPath

#255 Add infernalrestraints xPath scene scrapper
  SCENE-SCRAPABLE.md
  scrapers/infernalrestraints.yml
Labels: xPath

#230 Adding a python based scraper for performers using the stash sqlite database.
  scrapers/stash-sqlite.py
  scrapers/stash-sqlite.yml
Labels: script

#249 Add ClubSeventeen xPath scene, gallery scraper
  README.md
  SCENE-SCRAPABLE.md
  scrapers/ClubSeventeen.yml
Labels: xPath

#253 Add HarmonyVision xPath movie,scene scraper
  README.md
  SCENE-SCRAPABLE.md
  scrapers/HarmonyVision.yml
Labels: xPath

#265 Create .gitattributes
  .gitattributes
  scrapers/FemDomEmpire.yml
  scrapers/Firstanalquest.yml
  scrapers/Fistertwister.yml
  scrapers/FittingRoom.yml
  scrapers/Mandyflores.yml
  scrapers/Modelhub.yml
  scrapers/PervCity.yml
  scrapers/Private.yml
  scrapers/Puffynetwork.yml
  scrapers/Teencoreclub.yml
  scrapers/TheNude.yml
  scrapers/TheScoreGroup.yml
  scrapers/Vipissy.yml
  scrapers/Xnxx.yml
  scrapers/Xtube.yml
  scrapers/Xvideos.yml
  scrapers/xbvrdb.py
Labels: enhancement

#259 update image and tags for hucows scraper
  scrapers/Hucows.yml
Labels: fix

#264 Add ScrewMeToo ( former Dateslam ) xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/ScrewMeToo.yml
Labels: xPath

#277 Add dates,tweak nympho.yml
  scrapers/nympho.yml
Labels: enhancement

#272 Add scene by fragment to Pornhub
  scrapers/Pornhub.yml
Labels: enhancement

#280 [Meta] Scraper Schema
  .gitignore
  README.md
  validate.js
  validator/index.js
  validator/package.json
  validator/scraper.schema.json
  validator/yarn.lock
Labels: utility

#281 Update PornDB.yml
  scrapers/PornDB.yml
Labels: fix

#274 Create ExpliciteArt.yml
  scrapers/ExpliciteArt.yml
Labels: xPath

#276 Create HouseOFyre.yml
  scrapers/HouseOfFyre.yml
Labels: xPath

#268 Adds performer xPath scraper to BaDoink
  SCRAPERS-LIST.md
  scrapers/BaDoink.yml
Labels: enhancement

#282 Combat Zone
  SCRAPERS-LIST.md
  scrapers/CombatZone.yml
Labels: xPath

#285 Add movie,performer URL to JJ scenescraper
  scrapers/JulesJordan.yml
Labels: enhancement

#284 Fix ThePorndDB filename parsing
  scrapers/ThePornDB.yml
Labels: fix

#286 Update AdultEmpire
  SCRAPERS-LIST.md
  scrapers/AdultEmpire.yml
Labels: enhancement

#278 AdultEmpireCash
  SCRAPERS-LIST.md
  scrapers/AdultEmpireCash.yml
  scrapers/JaysPov.yml
  scrapers/Mypervyfamily.yml
  scrapers/lethalhardcore.yml
Labels: xPath

#289 Add Hegre xPath Scraper
  SCRAPERS-LIST.md
  scrapers/Hegre.yml
Labels: xPath

#288 Update Nubiles scraper
  SCRAPERS-LIST.md
  scrapers/Nubiles.yml
Labels: xPath

#294 Update Babepedia.yml
  scrapers/Babepedia.yml
Labels: fix

#291 Update SARJ-LLC to pull wide scene covers and allow galleryByURL
  scrapers/SARJ-LLC.yml
Labels: enhancement

#293 add shagmag gallery scraper
  SCRAPERS-LIST.md
  scrapers/shagmag.yml
Labels: xPath

#295 Add wtfpass xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/Wtfpass.yml
Labels: xPath
