Repository stashapp/CommunityScrapers, pull requests merged in 2020-10, with the labels that each got.

#194 Adds GirlsRimming xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/GirlsRimming.yml
Labels: xPath

#197 Add homeclips and funbags scraper
  SCENE-SCRAPABLE.md
  scrapers/Voyeurweb.yml
Labels: xPath

#190 Add scraper based on xbvr sqlite database
  scrapers/xbvrdb.py
  scrapers/xbvrdb.yml
Labels: script

#198 Add SpankBang xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/SpankBang.yml
Labels: xPath

#201 Adds motherless xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/Motherless.yml
Labels: xPath

#203 Adds FilthyFamily xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/FilthyFamily.yml
Labels: xPath

#204 Add Boundhoneys xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/Boundhoneys.yml
Labels: xPath

#200 Add PacoPacoMama xPath scene scraper
  SCENE-SCRAPABLE.md
  scrapers/Paco.yml
Labels: xPath

#207 fix studio in GammaEntertainment
  scrapers/GammaEntertainment.yml
Labels: fix

#205 Add ExCoGi xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/ExCoGi.yml
Labels: xPath

#209 Add YouPorn xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/YouPorn.yml
Labels: xPath

#208 Add WatchMyGF xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/WatchMyGF.yml
Labels: xPath

#212 Add FemDomEmpire Scraper
  scrapers/FemDomEmpire.yml
Labels: xPath

#215 Add StasyQ xPath scraper
  README.md
  SCENE-SCRAPABLE.md
  scrapers/StasyQ.yml
Labels: xPath

#206 Add PervCity.com scraper
  scrapers/PervCity.yml
Labels: xPath

#218 Adds BoxTruckSex xPath scene scraper
  SCENE-SCRAPABLE.md
  scrapers/BoxTruckSex.yml
Labels: xPath

#220 Update Javlibrary
  README.md
  SCENE-SCRAPABLE.md
  scrapers/javlibrary.yml
Labels: enhancement

#82 Adds 21Roles xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/21Roles.yml
Labels: xPath

#225 Add JavHD xPath scene scraper
  SCENE-SCRAPABLE.md
  scrapers/JavHD.yml
Labels: xPath

#226 Update javlibrary.yml (Note)
  scrapers/javlibrary.yml
Labels: enhancement

#229 Adding a way to correct the Title for Javlibrary
  scrapers/javlibrary.yml
Labels: enhancement

#222 Allow AdultDVDEmpire to also function on scenes + tweaks
  scrapers/AdultEmpire.yml
Labels: enhancement

#80 Adds SARJ-LLC xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/SARJ-LLC.yml
Labels: xPath

#213 Add Fitting-Room Scraper
  scrapers/FittingRoom.yml
Labels: xPath

#246 add MPLStudios
  README.md
  SCENE-SCRAPABLE.md
  scrapers/MPLStudios.yml
Labels: xPath

#245 Add sceneByFragment for Heyzo, Caribbeancom
  scrapers/Carib.yml
  scrapers/Heyzo.yml
Labels: enhancement

#242 Hentai site Galleries Scraper (xPath)
  README.md
  scrapers/hentai2read.yml
  scrapers/nhentai.yml
Labels: xPath

#247 add sceneByFragment for Kink
  scrapers/Kink.yml
Labels: enhancement

#237 Adding AussieFelatioQueens.com scraper
  SCENE-SCRAPABLE.md
  scrapers/AussieFelatioQueens.yml
Labels: CDP, xPath

#240 adding bruceandmorgan.com scraper
  SCENE-SCRAPABLE.md
  scrapers/bruceandmorgan.yml
Labels: CDP, xPath
