Repository stashapp/CommunityScrapers, pull requests merged in 2020-09, with the labels that each got.

#137 TransSensual own scraper and removed from RK
  scrapers/TransSensual.yml
Labels: xPath

#134 Partial add sites from GroobyNetwork
  SCENE-SCRAPABLE.md
  scrapers/GroobyNetwork-Partial.yml
Labels: xPath

#158 Adds Kelly Madison Media xPath CDP scraper
  SCENE-SCRAPABLE.md
  scrapers/KellyMadisonMedia.yml
Labels: CDP, xPath

#169 Update RealityKingsOL.yml xpath scraper
  scrapers/RealityKingsOL.yml
Labels: fix

#177 Added DreamTranny scraper
  SCENE-SCRAPABLE.md
  scrapers/DreamTranny.yml
Labels: xPath

#176 Add mandyflores xpath scraper
  SCENE-SCRAPABLE.md
  scrapers/Mandyflores.yml
Labels: xPath

#127 Adding several Scrapers
  SCENE-SCRAPABLE.md
  scrapers/AbuseMe.yml
  scrapers/Andomark.yml
  scrapers/Cherrypimps.yml
  scrapers/Cumlouder.yml
  scrapers/DDFNetwork.yml
  scrapers/FILF.yml
  scrapers/Mormongirlz.yml
  scrapers/PaperStreetMedia.yml
  scrapers/PlumperPass.yml
  scrapers/RawAttack.yml
  scrapers/SweetFemdom.yml
  scrapers/TheScoreGroup.yml
  scrapers/girlsway.yml
  scrapers/kinkyfamily.yml
  scrapers/lethalhardcore.yml
  scrapers/nympho.yml
  scrapers/pornworld.yml
  scrapers/r18.yml
  scrapers/sexuallybroken.yml
  scrapers/sugarcookie.yml
  scrapers/toughlovex.yml
  scrapers/trafficpimps.yml
  scrapers/wankz.yml
Labels: CDP, xPath

#193 Add LoveHerFeet xPath scraper
  SCENE-SCRAPABLE.md
  scrapers/LoveHerFeet.yml
Labels: xPath

#192 Add Frolicme xPath scene scraper
  SCENE-SCRAPABLE.md
  scrapers/FrolicMe.yml
Labels: xPath

#163 Adding Lustery xpath scraper
  SCENE-SCRAPABLE.md
  scrapers/Lustery.yml
Labels: xPath

#164 Adding VNAGirls series of sites containing websites for individual models
  SCENE-SCRAPABLE.md
  scrapers/VNAGirls.yml
Labels: xPath
