Repository stashapp/CommunityScrapers, pull requests merged in 2021-06, with the labels that each got.

#558 add MVG.yml
  SCRAPERS-LIST.md
  scrapers/MVG.yml
Labels: xPath

#584 add ClaudiaMarie.yml
  SCRAPERS-LIST.md
  scrapers/ClaudiaMarie.yml
Labels: xPath

#583 Update AdultimeAPI.py
  scrapers/AdultimeAPI.py
Labels: enhancement

#587 Fix bilingual scene descriptions
  scrapers/HelixStudios.yml
Labels: enhancement

#581 Add XConfessions xPath scene, movie scraper
  SCRAPERS-LIST.md
  scrapers/XConfessions.yml
Labels: xPath

#585 add InterrcialPass.com to html scene scrapers
  SCRAPERS-LIST.md
  scrapers/InterracialPass.yml
Labels: xPath

#590 Add ManyVids performer tag scraping support
  scrapers/ManyVids.yml
Labels: enhancement

#593 Fix Performers on SwallowSalon
  scrapers/AmateurAllure.yml
Labels: fix

#595 Fix Vixen scraper
  scrapers/vixenNetwork.py
Labels: fix

#588 Update javdb.yml
  scrapers/javdb.yml
Labels: fix

#589 Velvetveronica
  SCRAPERS-LIST.md
  scrapers/VelvetVeronica.yml
Labels: xPath

#597 Update FinishesTheJob.yml
  scrapers/FinishesTheJob.yml
Labels: fix

#598 add POVR.yml
  SCRAPERS-LIST.md
  scrapers/POVR.yml
Labels: xPath

#596 add MomXXX.yml
  SCRAPERS-LIST.md
  scrapers/Mypervmom.yml
Labels: xPath

#591 Xpath scraper for goddesssnow.com
  SCRAPERS-LIST.md
  scrapers/GoddessSnow.yml
Labels: xPath

#599 LetsDoeIt - Remove extra text in title
  scrapers/LetsDoeIt.yml
Labels: enhancement

#601 Create ShylaJ.yml
  SCRAPERS-LIST.md
  scrapers/ShylaJ.yml
Labels: xPath

#600 Add IWantClips to the scrapers.
  SCRAPERS-LIST.md
  scrapers/IWantClips.yml
Labels: xPath

#604 Fix PureTaboo
  scrapers/PureTaboo.yml
Labels: fix

#603 Fix image part for transangels
  scrapers/RealityKingsOL.yml
Labels: fix

#605 PornDB (URL): Remove CDP
  SCRAPERS-LIST.md
  scrapers/PornDB.yml
Labels: fix

#607 Update PuffyNetworkSite.yml
  scrapers/PuffyNetworkSite.yml
Labels: fix

#608 Create RealJamVR
  SCRAPERS-LIST.md
  scrapers/RealJamVR.yml
Labels: xPath

#609 create StagCollective.yml
  SCRAPERS-LIST.md
  scrapers/StagCollective.yml
Labels: xPath

#606 create BamVisions.yml
  SCRAPERS-LIST.md
  scrapers/BamVisions.yml
Labels: xPath

#612 add Baberotica.yml
  SCRAPERS-LIST.md
  scrapers/Baberotica.yml
Labels: xPath

#602 Fix MyDirtyHobby
  scrapers/MyDirtyHobby.yml
Labels: fix
