Repository stashapp/CommunityScrapers, pull requests merged in 2021-01, with the labels that each got.

#325 Add Oldgoesyoung (Covers trickyoldteacher and spoiledvirgins)
  SCRAPERS-LIST.md
  scrapers/AssTraffic.yml
  scrapers/DogFart.yml
  scrapers/GroobyNetwork-Partial.yml
  scrapers/MindGeek.yml
  scrapers/OldGoesYoung.yml
  scrapers/PaperStreetMedia.yml
  scrapers/RealityKingsOL.yml
  scrapers/SweetyX.yml
Labels: xPath

#329 Updating GirsOutWest scraper.
  SCRAPERS-LIST.md
  scrapers/GirlsOutWest.yml
Labels: fix

#331 Add dickdrainers xPath scraper
  SCRAPERS-LIST.md
  scrapers/Dickdrainers.yml
Labels: xPath

#335 Fix image for nympho.com
  scrapers/nympho.yml
Labels: fix

#334 Fix TGF (update from discord channel)
  scrapers/Tonightsgirlfriend.yml
Labels: fix

#320 data18
  SCRAPERS-LIST.md
  scrapers/data18.yml
Labels: xPath

#339 Add studio to Dogfart.yml
  scrapers/DogFart.yml
Labels: enhancement

#342 Add scene movie to Bang.yml
  scrapers/Bang.yml
Labels: enhancement

#345 Update censor list for R18
  scrapers/javlibrary.yml
  scrapers/r18.yml
Labels: enhancement

#346 Add store.freeones.com xPath scene and movie scraper
  SCRAPERS-LIST.md
  scrapers/FreeonesStore.yml
Labels: xPath

#347 Deviante (+SubSite) XPath Scraper
  SCRAPERS-LIST.md
  scrapers/deviante.yml
  scrapers/devianteNetwork.yml
Labels: xPath

#337 Insex update
  SCRAPERS-LIST.md
  scrapers/insex.yml
  scrapers/insexOL.yml
Labels: enhancement, xPath

#348 Fix image, tags in AbbbyWinters
  scrapers/AbbyWinters.yml
Labels: fix

#349 Update PornDB
  scrapers/PornDB.yml
Labels: fix

#352 Clips4sale fix
  scrapers/Clips4Sale.yml
Labels: fix

#351 added scraper for chastitybabes.com
  SCRAPERS-LIST.md
  scrapers/chastitybabes.yml
Labels: xPath

#350 Passionxxx xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/Passionxxx.yml
Labels: xPath
