Repository stashapp/CommunityScrapers, pull requests merged in 2021-11, with the labels that each got.

#755 create ThirdRockEnt
  SCRAPERS-LIST.md
  scrapers/AnalizedNetwork.yml
  scrapers/ThirdRockEnt.yml
Labels: xPath, fix

#743 add premiumbukkake scrapper
  SCRAPERS-LIST.md
  scrapers/PremiumBukkake.py
  scrapers/PremiumBukkake.yml
Labels: script

#759 add brattymilf
  SCRAPERS-LIST.md
  scrapers/Nubiles.yml
Labels: xPath

#762 Update IAFD performer image xpath
  scrapers/IAFD.py
Labels: script, fix

#756 add z-filmz-originals
  SCRAPERS-LIST.md
  scrapers/Z-Filmz-Originals.yml
Labels: xPath

#742 add pornhubpremium scraper
  SCRAPERS-LIST.md
  scrapers/PornhubPremium.yml
Labels: xPath

#764 Fix removal of suffix text on letsdoeit
  scrapers/LetsDoeIt.yml
Labels: fix

#765 Add StraponDreamer.yml
  SCRAPERS-LIST.md
  scrapers/StraponDreamer.yml
Labels: xPath

#769 [Javlibrary Python] Adding option to split tag if contains `,`/`·`
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: enhancement

#738 Update Mindgeek API (Local + Marker support)
  scrapers/MindGeekAPI.py
  scrapers/MindGeekAPI.yml
Labels: enhancement

#773 Xbvr scraper support for galleries
  scrapers/xbvrdb.py
  scrapers/xbvrdb.yml
Labels: enhancement

#761 Traxxx Scrapers
  scrapers/Traxxx.py
  scrapers/Traxxx.yml
  scrapers/py_common/log.py
  scrapers/traxxx_interface.py
Labels: script

#770 Add Kinkbomb.com
  SCRAPERS-LIST.md
  scrapers/KinkBomb.yml
Labels: xPath

#774 This gallery scraper will copy metadata from a linked scene.
  scrapers/CopyFromScene.py
  scrapers/CopyFromScene.yml
Labels: script

#775 IFeelMyself fixes
  scrapers/IFeelMyself.py
  scrapers/IFeelMyself.yml
Labels: fix

#757 Added Studio to MilfVR and aditional image extraction from NaughtyAmerica for VR scenes
  scrapers/MilfVR.yml
  scrapers/NaughtyAmerica.yml
Labels: enhancement, fix

#780 AdultEmpire fixes
  SCRAPERS-LIST.md
  scrapers/AdultEmpireCash.yml
  scrapers/AdultEmpireNew.yml
Labels: CDP

#779 Added Babesandstars.com
  SCRAPERS-LIST.md
  scrapers/Babes&Stars.yml
Labels: xPath

#776 AVEntertainments xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/AVE.yml
Labels: xPath

#787 VirtualPorn.com XPath scene scraper
  SCRAPERS-LIST.md
  scrapers/VirtualPorn.yml
Labels: xPath

#781 Add Topwebmodels python scraper
  SCRAPERS-LIST.md
  scrapers/TopWebModels.py
  scrapers/TopWebModels.yml
Labels: script

#795 Update PaperStreetMedia
  SCRAPERS-LIST.md
  scrapers/PaperStreetMedia.yml
Labels: xPath
