Repository stashapp/CommunityScrapers, pull requests merged in 2021-08, with the labels that each got.

#672 add SwallowBay.yml
  SCRAPERS-LIST.md
  scrapers/SwallowBay.yml
Labels: xPath

#664 Update Jav Python
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: enhancement, script

#665 Update ThePornDB to use the parent not the site name
  scrapers/ThePornDB.yml
Labels: enhancement

#660 add NakedSword
  SCRAPERS-LIST.md
  scrapers/NakedSword.yml
Labels: xPath

#661 Added Hijab Hookup to Paper Street Media yml
  scrapers/PaperStreetMedia.yml
Labels: enhancement

#674 Update Vixen python
  scrapers/vixenNetwork.py
  scrapers/vixenNetwork.yml
Labels: fix, script

#650 Dorcel: Add Movie Scrapper
  SCRAPERS-LIST.md
  scrapers/DorcelClub.yml
Labels: enhancement

#651 Add Transerotica support
  SCRAPERS-LIST.md
  scrapers/Transerotica.yml
Labels: xPath

#652 Grooby: Add TGirls.porn
  SCRAPERS-LIST.md
  scrapers/GroobyNetwork-Partial.yml
Labels: enhancement

#657 add GymRotic
  SCRAPERS-LIST.md
  scrapers/GymRotic.yml
Labels: xPath

#681 add MenAtPlay.yml
  SCRAPERS-LIST.md
  scrapers/MenAtPlay.yml
Labels: xPath

#682 add AmelieLou.yml
  SCRAPERS-LIST.md
  scrapers/AmelieLou.yml
Labels: xPath

#683 add SmokingMina.yml
  SCRAPERS-LIST.md
  scrapers/SmokingMina.yml
Labels: xPath

#679 Update PaperStreetMedia.yml
  SCRAPERS-LIST.md
  scrapers/PaperStreetMedia.yml
Labels: enhancement

#611 Add new scraper for staxus.com
  SCRAPERS-LIST.md
  scrapers/Staxus.yml
Labels: xPath

#656 Add TrikePatrol.yml / TukTukPatrol.yml xPath scene/performer scrapers
  SCRAPERS-LIST.md
  scrapers/TrikePatrol.yml
  scrapers/TukTukPatrol.yml
  scrapers/VegasDreamsLLC.yml
Labels: xPath

#663 add Pornditos
  scrapers/Pornditos.yml
Labels: xPath

#680 Update SexLikeReal.yml
  scrapers/SexLikeReal.yml
Labels: fix

#687 Update pornworld.yml (Xpath)
  scrapers/pornworld.yml
Labels: enhancement

#666 Rework AdultimeAPI scraper
  SCRAPERS-LIST.md
  scrapers/AdultimeAPI.py
  scrapers/AdultimeAPI.yml
Labels: enhancement, script

#667 Rework Mindgeek Scraper
  scrapers/MindGeekAPI.py
  scrapers/MindGeekAPI.yml
Labels: enhancement, script

#670 Update Jav python (R18 API support)
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: enhancement, script

#692 Fixing ThePornDB.yml (Perf scene)
  scrapers/ThePornDB.yml
Labels: fix

#693 Update IAFD.py performer url xpath
  scrapers/IAFD.py
Labels: fix

#694 Fix bug Adultime API
  scrapers/AdultimeAPI.py
  scrapers/AdultimeAPI.yml
Labels: fix

#697 Update ZeroTolerance.yml
  scrapers/ZeroTolerance.yml
Labels: xPath, fix

#696 Add Perfect Gonzo sites
  SCRAPERS-LIST.md
  scrapers/AssTraffic.yml
  scrapers/PerfectGonzo.yml
Labels: xPath, fix
