Repository stashapp/CommunityScrapers, pull requests merged in 2021-07, with the labels that each got.

#594 Adding multiscrape python based scraper.
  scrapers/multiscrape.py
  scrapers/multiscrape.yml
Labels: xPath

#625 GammaEntertainment: support Wicked movies
  SCRAPERS-LIST.md
  scrapers/GammaEntertainment.yml
Labels: enhancement

#627 update NewSensationsMain
  scrapers/GammaEntertainment.yml
  scrapers/NewSensationsMain.yml
Labels: enhancement, fix

#622 Atkhairy update
  SCRAPERS-LIST.md
  scrapers/ATKHairy.yml
Labels: enhancement

#613 fixes scraper break if model doesn't have bio
  scrapers/SARJ-LLC.py
Labels: fix

#615 add BabeArchives.yml
  SCRAPERS-LIST.md
  scrapers/BabeArchives.yml
Labels: xPath

#616 add WatchYouJerk.yml
  SCRAPERS-LIST.md
  scrapers/WatchYouJerk.yml
Labels: xPath

#618 add PlayWithRae.yml
  SCRAPERS-LIST.md
  scrapers/PlayWithRae.yml
Labels: xPath

#619 add EricJohnsSexAdventures.yml
  SCRAPERS-LIST.md
  scrapers/EricJohnsSexAdventures.yml
Labels: xPath

#614 add DigitalDesire.yml
  SCRAPERS-LIST.md
  scrapers/DigitalDesire.yml
Labels: xPath

#617 add SofieMariexxx.yml
  SCRAPERS-LIST.md
  scrapers/SofieMariexxx.yml
Labels: xPath

#620 add Waybig.yml
  SCRAPERS-LIST.md
  scrapers/Waybig.yml
Labels: xPath

#623 add Only3xGirls.yml
  SCRAPERS-LIST.md
  scrapers/Only3xGirls.yml
Labels: xPath

#631 PaperStreeMedia: Add FreeuseMilf
  SCRAPERS-LIST.md
  scrapers/PaperStreetMedia.yml
Labels: enhancement

#630 Update AdultimeAPI scraper (byURL)
  scrapers/AdultimeAPI.py
Labels: enhancement, fix, script

#633 Update things for JAV scraper
  scrapers/JavLibrary.yml
  scrapers/JavLibrary_python.py
  scrapers/r18.yml
Labels: enhancement

#635 Update houseofgord.yml
  scrapers/HouseOfGord.yml
Labels: fix

#632 add GirlsUnderArrest.yml
  SCRAPERS-LIST.md
  scrapers/GirlsUnderArrest.yml
Labels: xPath

#640 Update deviante.yml
  scrapers/Deviante.yml
Labels: fix

#636 Diabolic
  SCRAPERS-LIST.md
  scrapers/Diabolic.yml
Labels: xPath

#637 Subspaceland
  SCRAPERS-LIST.md
  scrapers/SubspaceLand.yml
Labels: xPath

#641 add HeavyOnHotties.yml
  SCRAPERS-LIST.md
  scrapers/HeavyOnHotties.yml
Labels: xPath

#638 Xpath Scraper for FreakMobMedia
  SCRAPERS-LIST.md
  scrapers/FreakMobMedia.yml
Labels: xPath

#644 create AllAnalAllTheTime.yml
  SCRAPERS-LIST.md
  scrapers/AllAnalAllTheTime.yml
  scrapers/VNAGirls.yml
Labels: xPath

#639 add DevilsTgirls.yml
  SCRAPERS-LIST.md
  scrapers/DevilsTgirls.yml
Labels: xPath

#643 Added scraper for vod section on SubbyHubby/ClubDom
  scrapers/SubbyHubby.yml
Labels: enhancement, xPath

#646 update PerfectGonzo.
  SCRAPERS-LIST.md
  scrapers/PerfectGonzo.yml
Labels: xPath

#653 add FamilySexMassage
  SCRAPERS-LIST.md
  scrapers/FamilySexMassage.yml
Labels: xPath

#647 Add CruelGirlfriend xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/CruelGirlfriend.yml
Labels: xPath

#655 add FilthFlix.com
  SCRAPERS-LIST.md
  scrapers/FilthFlix.yml
Labels: xPath

#658 add CollegeUniform
  SCRAPERS-LIST.md
  scrapers/CollegeUniform.yml
Labels: xPath

#659 add Corbinfisher.com
  SCRAPERS-LIST.md
  scrapers/CorbinFisher.yml
Labels: xPath

#662 Add performer search to Waybig.yml
  scrapers/Waybig.yml
Labels: enhancement, xPath
