Repository stashapp/CommunityScrapers, pull requests merged in 2021-02, with the labels that each got.

#356 IAFD URL, Vixennetworks image fixes
  scrapers/Iafd.yml
  scrapers/vixenNetwork.yml
Labels: fix

#361 Add BlackAmbush XPath Scraper
  SCRAPERS-LIST.md
  scrapers/blackambush.yml
Labels: xPath

#364 Update vixen scraper
  SCRAPERS-LIST.md
  scrapers/vixenNetwork.py
  scrapers/vixenNetwork.yml
Labels: script

#368 Update Legal Porno scraper to new domain
  SCRAPERS-LIST.md
  scrapers/LegalPorno.py
  scrapers/LegalPorno.yml
Labels: fix

#362 Teamskeet API ? (Script JSON)
  SCRAPERS-LIST.md
  scrapers/TeamSkeet.yml
  scrapers/Teamskeet.yml
  scrapers/TeamskeetJSON.py
Labels: script

#370 Create wetandpissy.yml
  SCRAPERS-LIST.md
  scrapers/PuffyNetworkSite.yml
Labels: xPath

#359 added scraper for lewrubens.com
  SCRAPERS-LIST.md
  scrapers/LewRubens.yml
Labels: xPath

#358 This is a python scraper to read torrent files for metadata.
  scrapers/torrent.py
  scrapers/torrent.yml
  scrapers/torrent_parser.py
Labels: script

#372 Add xPath scene scraper for Kin8tengoku
  SCRAPERS-LIST.md
  scrapers/Kin8tengoku.yml
Labels: xPath

#373 add Mylked.yml
  SCRAPERS-LIST.md
  scrapers/Mylked.yml
Labels: xPath

#357 MindGeek API (Python)
  scrapers/MindGeekAPI.py
  scrapers/MindGeekAPI.yml
Labels: script

#374 Consolidate ExploitedX scene scrapers into one
  SCRAPERS-LIST.md
  scrapers/Backroomcastingcouch.yml
  scrapers/ExCoGi.yml
  scrapers/ExploitedX.yml
Labels: enhancement, fix

#379 Best effort solution to descriptions with lists on thetrainingofo
  scrapers/Kink.yml
Labels: enhancement

#376 add evolvedfightslez.yml
  SCRAPERS-LIST.md
  scrapers/evolvedfightslez.yml
Labels: xPath

#381 Fix found_scene_id extraction from scene URL
  scrapers/MindGeekAPI.py
Labels: fix

#380 add peeonher.yml
  SCRAPERS-LIST.md
  scrapers/peeonher.yml
Labels: xPath

#363 added xpath scraper for houseofgord.com
  SCRAPERS-LIST.md
  scrapers/houseofgord.yml
Labels: xPath

#387 Move VixenNetwork default JSON save location
  scrapers/vixenNetwork.py
  scrapers/vixenNetwork.yml
Labels: enhancement

#394 Adding FreeuseFantasy to PaperStreetMedia.yml
  SCRAPERS-LIST.md
  scrapers/PaperStreetMedia.yml
Labels: enhancement

#375 Brazzers fix, now CDP is required
  SCRAPERS-LIST.md
  scrapers/Brazzers.yml
Labels: CDP, fix

#395 Update Spizoo.yml (Perf & Tags Selector)
  scrapers/Spizoo.yml
Labels: fix

#392 [meta] update schema
  scrapers/Mylked.yml
  validator/scraper.schema.json
Labels: enhancement, utility
