Repository stashapp/CommunityScrapers, pull requests merged in 2021-03, with the labels that each got.

#385 Adultime API scraper (Python script)
  scrapers/AdultimeAPI.py
  scrapers/AdultimeAPI.yml
Labels: script

#389 add privatecastings.yml
  SCRAPERS-LIST.md
  scrapers/privatecastings.yml
Labels: xPath

#390 add pantyjobs.yml
  SCRAPERS-LIST.md
  scrapers/pantyjobs.yml
Labels: xPath

#398 add wearehairy.yml
  SCRAPERS-LIST.md
  scrapers/wearehairy.yml
Labels: xPath

#401 feat(schema): support url query replace
  validator/scraper.schema.json
Labels: enhancement, utility

#391 Switch to a JSON scraper for SARJ-LLC (metartnetwork)
  SCRAPERS-LIST.md
  scrapers/SARJ-LLC.yml
Labels: JSON

#386 Added scraper for my-slavegirl.com
  SCRAPERS-LIST.md
  scrapers/my-slavegirl.yml
Labels: xPath

#396 add perfectgonzo.yml
  SCRAPERS-LIST.md
  scrapers/perfectgonzo.yml
Labels: xPath

#406 Update IKissGirls.yml
  scrapers/IKissGirls.yml
Labels: fix

#403 create pjgirls.yml
  SCRAPERS-LIST.md
  scrapers/pjgirls.yml
Labels: xPath

#405 add wankitnow.yml
  SCRAPERS-LIST.md
  scrapers/wankitnow.yml
Labels: xPath

#411 Update MindGeekAPI.py
  scrapers/MindGeekAPI.py
Labels: enhancement, fix

#408 Update JapanHDV.yml
  scrapers/JapanHDV.yml
Labels: fix

#409 Update Cumlouder.yml
  scrapers/Cumlouder.yml
Labels: fix

#400 ModelCentro Api (Python Script)
  SCRAPERS-LIST.md
  scrapers/ModelCentroAPI.py
  scrapers/ModelCentroAPI.yml
Labels: script

#402 Switch to a JSON scraper for 1pondo
  SCRAPERS-LIST.md
  scrapers/1pondo.yml
Labels: JSON, enhancement

#410 create vogov.yml
  SCRAPERS-LIST.md
  scrapers/vogov.yml
Labels: xPath

#407 add lethalpass.yml
  SCRAPERS-LIST.md
  scrapers/lethalpass.yml
Labels: xPath

#420 Update AdultimeAPI.py
  scrapers/AdultimeAPI.py
Labels: fix

#421 Adds some verbosity to the requests errors
  scrapers/vixenNetwork.py
Labels: enhancement

#388 add karatmedia.yml xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/karatmedia.yml
Labels: xPath

#418 add brickyates.yml
  SCRAPERS-LIST.md
  scrapers/brickyates.yml
Labels: xPath

#419 add auntykathy.yml
  SCRAPERS-LIST.md
  scrapers/auntykathy.yml
Labels: xPath

#423 [validator] support performer tags
  validator/scraper.schema.json
Labels: enhancement, utility

#399 add sapphix.yml
  SCRAPERS-LIST.md
  scrapers/sapphix.yml
Labels: xPath

#424 Performer tags for Brazzers
  SCRAPERS-LIST.md
  scrapers/Brazzers.yml
Labels: enhancement

#422 Fix atkexotics (add cookies)
  SCRAPERS-LIST.md
  scrapers/ATKExotics.yml
Labels: fix

#437 Adding Pure-BBW
  SCRAPERS-LIST.md
  scrapers/Pure-BBW.yml
Labels: xPath

#438 Adding Desperate Amateurs
  SCRAPERS-LIST.md
  scrapers/DesperateAmateurs.yml
Labels: xPath

#427 add hushpass.yml
  SCRAPERS-LIST.md
  scrapers/hushpass.yml
Labels: xPath

#435 add angelasommers.yml
  SCRAPERS-LIST.md
  scrapers/angelasommers.yml
Labels: xPath

#439 Fix validation errors (ATKexotics and superbemodels)
  scrapers/ATKExotics.yml
  scrapers/superbemodels.yml
Labels: fix

#415 add bellapass.yml
  SCRAPERS-LIST.md
  scrapers/bellapass.yml
Labels: xPath

#443 fix title in Puretaboo
  scrapers/PureTaboo.yml
Labels: fix

#440 MindGeek fixes
  SCRAPERS-LIST.md
  scrapers/MindGeek.yml
Labels: fix

#441 add porncz.yml
  SCRAPERS-LIST.md
  scrapers/porncz.yml
Labels: xPath

#444 Add JeffsModels
  SCRAPERS-LIST.md
  scrapers/JeffsModels.yml
Labels: xPath

#447 fixed regex in get_from_url
  scrapers/vixenNetwork.py
Labels: fix

#449 Update MissaX.yml
  scrapers/MissaX.yml
Labels: fix

#454 Update LittleCapriceDreams.yml
  scrapers/LittleCapriceDreams.yml
Labels: fix

#455 add hussiemodels.yml
  SCRAPERS-LIST.md
  scrapers/hussiemodels.yml
Labels: xPath

#453 Update performer image scraper
  scrapers/performer-image-dir.py
  scrapers/performer-image-dir.yml
Labels: fix

#457 Add HobyBuchanon xPath scraper
  SCRAPERS-LIST.md
  scrapers/HobyBuchanon.yml
Labels: xPath
