Repository stashapp/CommunityScrapers, pull requests merged in 2021-05, with the labels that each got.

#491 add Hotmovies.yml
  SCRAPERS-LIST.md
  scrapers/Hotmovies.yml
Labels: xPath

#511 Ignore default images from TPDB
  scrapers/ThePornDB.yml
Labels: enhancement

#513 Paco fix
  scrapers/Paco.yml
Labels: fix

#514 Fix URL, add Title fallback for 1Pondo
  scrapers/1pondo.yml
Labels: enhancement

#495 add ffcsh.yml
  SCRAPERS-LIST.md
  scrapers/FFCSH.yml
Labels: xPath

#458 Add jacquieetmicheltv python scene scraper
  SCRAPERS-LIST.md
  scrapers/JacquieEtMichelTV.py
  scrapers/JacquieEtMichelTV.yml
Labels: script

#487 Pornhub added Image and different Profile scraping
  scrapers/Pornhub.yml
Labels: enhancement

#512 babepedia profile image selection
  scrapers/Babepedia.yml
Labels: enhancement

#519 Update AdultEmpireCash.yml
  scrapers/AdultEmpireCash.yml
Labels: enhancement

#518 add Amateurboxxx..yml
  SCRAPERS-LIST.md
  scrapers/AmateurBoxxx.yml
Labels: xPath

#517 Boundlife
  SCRAPERS-LIST.md
  scrapers/Boundlife.yml
Labels: xPath

#516 Dreamsofspanking
  SCRAPERS-LIST.md
  scrapers/DreamsOfSpanking.yml
Labels: xPath

#521 add VegasDreamworks.yml
  SCRAPERS-LIST.md
  scrapers/VegasDreamworks.yml
Labels: xPath

#523 update Oldgoesyoung
  SCRAPERS-LIST.md
  scrapers/OldGoesYoung.yml
Labels: enhancement

#522 add HandDomination.yml
  SCRAPERS-LIST.md
  scrapers/HandDomination.yml
Labels: xPath

#524 Fix vixen URL when json has null
  scrapers/vixenNetwork.py
Labels: fix

#529 add GlossTightsGlamour.yml
  SCRAPERS-LIST.md
  scrapers/GlossTightsGlamour.yml
Labels: xPath

#527 add BoppingBabes.yml
  SCRAPERS-LIST.md
  scrapers/BoppingBabes.yml
Labels: xPath

#528 add Plushies.yml
  SCRAPERS-LIST.md
  scrapers/Plushies.yml
Labels: xPath

#530 add Cospuri.yml
  SCRAPERS-LIST.md
  scrapers/Cospuri.yml
Labels: xPath

#533 add Pawged.yml
  SCRAPERS-LIST.md
  scrapers/Pawged.yml
Labels: xPath

#525 add Hentaied.yml
  SCRAPERS-LIST.md
  scrapers/Hentaied.yml
Labels: xPath

#532 Switch to a python scraper for IAFD
  SCRAPERS-LIST.md
  scrapers/IAFD.py
  scrapers/IAFD.yml
  scrapers/Iafd.yml
Labels: script

#536 add MongerInAsia.yml
  SCRAPERS-LIST.md
  scrapers/MongerInAsia.yml
Labels: xPath

#537 add Watch4Fetish.yml
  SCRAPERS-LIST.md
  scrapers/Watch4Fetish.yml
Labels: xPath

#540 add Gasm.yml
  SCRAPERS-LIST.md
  scrapers/GASM.yml
Labels: xPath

#541 Tweak javlibrary.yml (duration)
  scrapers/JavLibrary.yml
Labels: fix

#414 replace scraper for SARJ LLC with a script
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
Labels: script

#544 add Pinkoclub.yml
  SCRAPERS-LIST.md
  scrapers/Pinkoclub.yml
Labels: xPath

#545 Sarj llc improvements
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
Labels: enhancement, script

#546 add Pegasproductions.yml
  SCRAPERS-LIST.md
  scrapers/PegasProductions.yml
Labels: xPath

#551 fix image on loveherfeet xml scraper
  scrapers/LoveHerFeet.yml
Labels: fix

#552 Update DDFNetwork.yml
  scrapers/DDFNetwork.yml
Labels: fix

#548 Add Porndudecasting xPath scene and performer scraper
  SCRAPERS-LIST.md
  scrapers/PornDudeCasting.yml
Labels: xPath

#531 Update Mylf.yml (Tags)
  scrapers/Mylf.yml
Labels: enhancement

#547 Add Fit18 xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/Fit18.yml
Labels: xPath

#549 Add momcomesfirst to FamilyTherapyXXX
  SCRAPERS-LIST.md
  scrapers/FamilyTherapyXXX.yml
Labels: xPath

#550 Add swallowsalon to AmateurAllure.yml
  SCRAPERS-LIST.md
  scrapers/AmateurAllure.yml
Labels: xPath

#556 add TACAmateurs.yml
  SCRAPERS-LIST.md
  scrapers/TACAmateurs.yml
Labels: xPath

#557 add StrapOnCum.yml
  SCRAPERS-LIST.md
  scrapers/StrapOnCum.yml
Labels: xPath

#553 Add date to MaxHardcore
  SCRAPERS-LIST.md
  scrapers/MaxHardcore.yml
  validator/scraper.schema.json
Labels: enhancement

#559 add Femanic.yml
  SCRAPERS-LIST.md
  scrapers/Femanic.yml
Labels: xPath

#561 added URL to Carib
  scrapers/Carib.yml
Labels: enhancement, xPath

#562 add SissyPov.yml
  SCRAPERS-LIST.md
  scrapers/SissyPov.yml
Labels: xPath

#575 Fix performers in scenes for PornDB scraper
  scrapers/PornDB.yml
Labels: fix

#563 add PissyNetwork.yml
  SCRAPERS-LIST.md
  scrapers/PissyNetwork.yml
Labels: xPath

#564 add VlogXXX.yml
  SCRAPERS-LIST.md
  scrapers/VlogXXX.yml
Labels: xPath

#565 add LoneStarAngel.yml
  SCRAPERS-LIST.md
  scrapers/LoneStarAngel.yml
Labels: xPath

#566 add FFstockings.yml
  SCRAPERS-LIST.md
  scrapers/FFstockings.yml
Labels: xPath

#567 add LingerieTales.yml
  SCRAPERS-LIST.md
  scrapers/LingerieTales.yml
Labels: xPath

#569 add KinkyMistresses.yml
  SCRAPERS-LIST.md
  scrapers/KinkyMistresses.yml
Labels: xPath

#568 add SubbyHubby.yml
  SCRAPERS-LIST.md
  scrapers/SubbyHubby.yml
Labels: xPath

#543 fix encoding, set lang
  scrapers/JacquieEtMichelTV.py
  scrapers/JacquieEtMichelTV.yml
Labels: enhancement, script

#560 create extrapackage.yml
  SCRAPERS-LIST.md
  scrapers/ExtraPackage.yml
Labels: xPath

#570 add SwingerBlog.yml
  SCRAPERS-LIST.md
  scrapers/SwingerBlog.yml
Labels: xPath

#554 Create HelixStudios.yml
  SCRAPERS-LIST.md
  scrapers/HelixStudios.yml
Labels: xPath

#578 Update Clips4Sale.yml
  scrapers/Clips4Sale.yml
Labels: enhancement

#576 add SinsLife.yml
  SCRAPERS-LIST.md
  scrapers/SinsLife.yml
Labels: xPath

#577 add SubmissiveX.yml
  SCRAPERS-LIST.md
  scrapers/SubmissiveX.yml
Labels: xPath

#571 Update NewSensationsNetworkSites.yml
  scrapers/NewSensationsNetworkSites.yml
Labels: enhancement

#574 update Jhdv.yml
  SCRAPERS-LIST.md
  scrapers/Jhdv.yml
Labels: enhancement

#542 Add Madou Media scraper
  SCRAPERS-LIST.md
  scrapers/Madou.yml
Labels: xPath
