Repository stashapp/CommunityScrapers, pull requests merged in 2021-10, with the labels that each got.

#729 Update BaDoink.yml
  SCRAPERS-LIST.md
  scrapers/BaDoink.yml
Labels: enhancement, fix

#728 Update VRBangers.yml
  scrapers/VRBangers.yml
Labels: fix

#753 Adding pervtherapy and sisswap to PaperStreetMedia.yml
  SCRAPERS-LIST.md
  scrapers/PaperStreetMedia.yml
Labels: xPath

#684 Adding IMDB scraper, they do have some adult performers there.
  scrapers/IMDB.yml
Labels: xPath

#752 add shelovesblack
  SCRAPERS-LIST.md
  scrapers/LoveHerFeet.yml
Labels: xPath
