Repository stashapp/CommunityScrapers, pull requests merged in 2021-12, with the labels that each got.

#798 Update AMAMultimedia.yml
  scrapers/AMAMultimedia.yml
Labels: fix

#796 FuckedHard18 Scraper
  SCRAPERS-LIST.md
  scrapers/FuckedHard18.yml
Labels: xPath

#797 Update README.md (Update Stable/Dev)
  README.md
Labels: documentation

#800 Fix swallowed.com details (Nympho.yml)
  SCRAPERS-LIST.md
  scrapers/Nympho.yml
Labels: fix

#801 Genderx name fix
  SCRAPERS-LIST.md
  scrapers/GammaEntertainment.yml
Labels: fix

#802 add Danni.com
  SCRAPERS-LIST.md
  scrapers/Danni.yml
Labels: xPath

#803 Create ModelMediaUS scraper (Xpath)
  SCRAPERS-LIST.md
  scrapers/ModelMediaUS.yml
Labels: xPath

#804 Hentaied.com: Various fixes
  scrapers/Hentaied.yml
Labels: fix

#805 Update Nympho.yml
  scrapers/Nympho.yml
Labels: fix

#807 Move TransAngels to MindGeek.yml
  SCRAPERS-LIST.md
  scrapers/MindGeek.yml
  scrapers/RealityKingsOL.yml
Labels: fix

#809 Add Pornbox.com support
  SCRAPERS-LIST.md
  scrapers/Pornbox.yml
Labels: JSON

#810 Add StripzVR.yml
  SCRAPERS-LIST.md
  scrapers/StripzVR.yml
Labels: xPath

#811 Add Amateur Allure gallery support
  SCRAPERS-LIST.md
  scrapers/AmateurAllure.yml
Labels: enhancement

#790 [ThePornDB] Add date to search results at sceneSearch
  scrapers/ThePornDB.yml
Labels: enhancement

#782 Adultempire sceneByName Searching
  scrapers/AdultEmpire.yml
  scrapers/Pornhub.yml
Labels: enhancement, xPath

#815 multiscrape: pass url to scrape_performer
  scrapers/multiscrape.py
  scrapers/multiscrape.yml
Labels: fix

#813 Traxxx fixes
  scrapers/Traxxx.yml
  scrapers/traxxx_interface.py
Labels: enhancement, script, fix

#816 Add scraper for RandyBlue
  SCRAPERS-LIST.md
  scrapers/RandyBlue.yml
Labels: xPath

#793 Algolia Scraper (Adultime, filthykings, zerotolerancefilms, ...)
  SCRAPERS-LIST.md
  scrapers/AdultEmpireNew.yml
  scrapers/Algolia.py
  scrapers/Algolia_Adultime.yml
  scrapers/Algolia_disruptivefilms.yml
  scrapers/Algolia_filthykings.yml
  scrapers/Algolia_mypervyfamily.yml
  scrapers/Algolia_touchmywife.yml
  scrapers/Algolia_zerotolerancefilms.yml
  scrapers/ZeroTolerance.yml
  scrapers/py_common/config.py
  scrapers/py_common/graphql.py
  scrapers/py_common/log.py
Labels: enhancement, script, fix

#799 Unset birthdate if it can't be parsed to YYYY-MM-DD
  scrapers/IAFD.py
  scrapers/IAFD.yml
Labels: enhancement, script

#818 Add LucasEntertainment scraper
  SCRAPERS-LIST.md
  scrapers/LucasEntertainment.yml
Labels: xPath

#820 Update PlumperPass.yml
  scrapers/PlumperPass.yml
Labels: fix

#819 Improve HelixStudios scraper
  scrapers/HelixStudios.yml
Labels: enhancement, xPath

#823 Fixed PornHub fragment scene scraper
  scrapers/Pornhub.yml
Labels: enhancement, fix

#822 Add VRLatina.yml
  SCRAPERS-LIST.md
  scrapers/VRLatina.yml
Labels: xPath

#824 Update PureTaboo scrapper
  scrapers/PureTaboo.yml
Labels: xPath, fix

#825 add ThirdSexXXX scrapper
  SCRAPERS-LIST.md
  scrapers/ThirdSexXXX.yml
Labels: script

#827 Local ComicInfo.xml file
  scrapers/ComicInfoXML.py
  scrapers/ComicInfoXML.yml
  scrapers/py_common/graphql.py
Labels: script

#832 [Algolia] Explain py_common (Catch error)
  scrapers/Algolia.py
  scrapers/Algolia_Adultime.yml
  scrapers/Algolia_disruptivefilms.yml
  scrapers/Algolia_mypervyfamily.yml
  scrapers/Algolia_touchmywife.yml
  scrapers/Algolia_zerotolerancefilms.yml
  scrapers/py_common/graphql.py
Labels: enhancement, script, fix
