Repository stashapp/CommunityScrapers, pull requests merged in 2021-04, with the labels that each got.

#460 Update stash-sqlite scraper to use data image URLs
  scrapers/stash-sqlite.py
  scrapers/stash-sqlite.yml
Labels: enhancement

#461 add movie url to scene scrape
  scrapers/GammaEntertainment.yml
Labels: enhancement

#463 Update NewSensationsMain.yml
  scrapers/NewSensationsMain.yml
Labels: fix

#462 Update NewSensationsNetworkSites.yml
  scrapers/NewSensationsNetworkSites.yml
Labels: fix

#456 add vip4k.yml
  SCRAPERS-LIST.md
  scrapers/Vip4K.yml
Labels: xPath

#459 Add MyDirtyHobby xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/MyDirtyHobby.yml
Labels: xPath

#464 Added Texas Bukkake
  scrapers/TexasBukkake.yml
Labels: xPath

#470 add ClassLesbians.yml
  SCRAPERS-LIST.md
  scrapers/ClassLesbians.yml
Labels: xPath

#473 add Philavise.yml
  SCRAPERS-LIST.md
  scrapers/Philavise.yml
Labels: xPath

#472 added scraper for 5kteens.com/5kporn.com
  SCRAPERS-LIST.md
  scrapers/5KTeens.yml
Labels: xPath

#474 add FetishPros.yml
  SCRAPERS-LIST.md
  scrapers/FetishPro.yml
Labels: xPath

#477 add CatalinaCruz.yml
  SCRAPERS-LIST.md
  scrapers/Catalina Cruz.yml
Labels: xPath

#476 add LexiDona.yml
  SCRAPERS-LIST.md
  scrapers/LexiDona.yml
Labels: xPath

#479 add PlayboyPlus.yml
  SCRAPERS-LIST.md
  scrapers/PlayboyPlus.yml
Labels: xPath

#480 add VegasDreamsLLC.yml
  SCRAPERS-LIST.md
  scrapers/ScrewMeToo.yml
  scrapers/VegasDreamsLLC.yml
Labels: xPath

#482 add Nikki+Tera.yml
  SCRAPERS-LIST.md
  scrapers/NikkiAndTera.yml
Labels: xPath

#468 [validator] add support for `driver.headers`
  validator/scraper.schema.json
Labels: enhancement, utility

#478 [validator] add support for new performer fields
  scrapers/FreeonesCommunity.yml
  validator/scraper.schema.json
Labels: enhancement, utility

#481 add Oldje.yml
  SCRAPERS-LIST.md
  scrapers/Oldje.yml
Labels: xPath

#486 Add extra image selector for NaughtyAmerica
  scrapers/NaughtyAmerica.yml
Labels: fix

#488 AMAMultimedia: Higher resolution images, sort URLs
  scrapers/AMAMultimedia.yml
Labels: enhancement

#492 add Joybear.yml
  SCRAPERS-LIST.md
  scrapers/JoyBear.yml
Labels: xPath

#497 add Lasublime.yml
  SCRAPERS-LIST.md
  scrapers/Lasublime.yml
Labels: xPath

#489 add Jhdv.yml
  SCRAPERS-LIST.md
  scrapers/Jhdv.yml
Labels: xPath

#501 add MadeInCanada.yml
  SCRAPERS-LIST.md
  scrapers/MadeInCanada.yml
Labels: xPath

#508 Update NewSensationsNetworkSites.yml
  scrapers/NewSensationsNetworkSites.yml
Labels: fix

#500 add Hitzefrei.yml
  SCRAPERS-LIST.md
  scrapers/Hitzefrei.yml
Labels: xPath

#499 Add details, weight, hair color to Babepedia
  scrapers/Babepedia.yml
Labels: enhancement

#502 add PortaGloryhole.yml
  SCRAPERS-LIST.md
  scrapers/PortaGloryhole.yml
Labels: xPath

#503 add MaxHardcore.yml
  SCRAPERS-LIST.md
  scrapers/MaxHardcore.yml
Labels: xPath

#509 Fix tags for ThePornDB json scraper
  scrapers/ThePornDB.yml
Labels: fix

#493 Remove <strong> from GammaEntertainment details
  scrapers/GammaEntertainment.yml
Labels: enhancement

#506 add GenuineSin.yml
  SCRAPERS-LIST.md
  scrapers/GenuineSin.yml
Labels: xPath

#504 add HollyRandall.yml
  SCRAPERS-LIST.md
  scrapers/HollyRandall.yml
Labels: xPath
