Repository stashapp/CommunityScrapers, pull requests merged in 2021-09, with the labels that each got.

#699 Update Babepedia.yml (Death date)
  scrapers/Babepedia.yml
Labels: enhancement

#698 Adding selfiesuck site
  SCRAPERS-LIST.md
  scrapers/SelfieSuck.yml
Labels: xPath

#691 Add MilfTugs.yml xPath scene/performer scraper
  SCRAPERS-LIST.md
  scrapers/MilfTugs.yml
Labels: xPath

#704 add LustReality
  SCRAPERS-LIST.md
  scrapers/LustReality.yml
Labels: xPath

#701 add TabooHeat.yml
  SCRAPERS-LIST.md
  scrapers/TabooHeat.yml
Labels: xPath

#712 validator: support `sceneByName`
  validator/index.js
  validator/scraper.schema.json
Labels: enhancement, utility

#703 Sarj llc improvements
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
Labels: enhancement

#706 add slayed to vixen scraper
  SCRAPERS-LIST.md
  scrapers/vixenNetwork.yml
Labels: enhancement

#714 Support sceneByName for javdb
  SCRAPERS-LIST.md
  scrapers/javdb.yml
Labels: enhancement

#702 Switch to python for Fit18
  SCRAPERS-LIST.md
  scrapers/Fit18.py
  scrapers/Fit18.yml
Labels: script, fix

#707 Update Backroomcastingcouch
  scrapers/Backroomcastingcouch.yml
Labels: fix

#708 Update ThePornDB.yml (SearchByName)
  SCRAPERS-LIST.md
  scrapers/ThePornDB.yml
Labels: enhancement

#718 Update VirtualTaboo.yml, WankzVR.yml and VRHush.yml
  SCRAPERS-LIST.md
  scrapers/VRHush.yml
  scrapers/VirtualTaboo.yml
  scrapers/WankzVR.yml
Labels: enhancement

#719 Update SARJ-LLC scraper to use new logging
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
Labels: enhancement, fix

#709 Update JavLibrary.yml (SearchByName)
  SCRAPERS-LIST.md
  scrapers/JavLibrary.yml
Labels: enhancement

#720 Update VRBangers.yml
  SCRAPERS-LIST.md
  scrapers/VRBangers.yml
Labels: enhancement, fix

#722 SARJ-LLC: add sceneByName support
  SCRAPERS-LIST.md
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
Labels: enhancement

#710 Update AdultimeAPI (SearchByName)
  scrapers/AdultimeAPI.py
  scrapers/AdultimeAPI.yml
Labels: enhancement

#723 Add sceneByName support for vipissy scraper
  SCRAPERS-LIST.md
  scrapers/Vipissy.yml
Labels: enhancement

#713 Update Javlibrary Python (sceneByName)
  SCRAPERS-LIST.md
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: enhancement

#711 Update MindGeekAPI (SearchByName)
  scrapers/MindGeekAPI.py
  scrapers/MindGeekAPI.yml
Labels: enhancement

#725 Added TwmVRnet.yml
  SCRAPERS-LIST.md
  scrapers/TeenMegaWorld.yml
  scrapers/TmwVRnet.yml
Labels: enhancement, fix

#724 Fix tags and image problems, added movie scraper (CzechVR).
  SCRAPERS-LIST.md
  scrapers/CzechVR.yml
Labels: enhancement, fix
