Repository stashapp/CommunityScrapers, pull requests merged in 2022-01, with the labels that each got.

#814 Data18.com has restructured their site
  scrapers/data18.yml
Labels: fix

#835 Move SpankMonster to AdultEmpireCash
  SCRAPERS-LIST.md
  scrapers/AdultEmpireCash.yml
  scrapers/ModelCentroAPI.yml
Labels: fix

#834 Add performer scraper for JapanHDV
  scrapers/JapanHDV.yml
Labels: enhancement, CDP

#848 Update Babepedia scraper (Ethnicity missing)
  scrapers/Babepedia.yml
Labels: fix

#828 Add Kristen Bjorn scraper
  SCRAPERS-LIST.md
  scrapers/KristenBjorn.yml
Labels: xPath

#839 William Higgins sites
  SCRAPERS-LIST.md
  scrapers/Williamhiggins.yml
Labels: xPath

#846 Added Czecgav sites
  SCRAPERS-LIST.md
  scrapers/Czechav.yml
Labels: enhancement, xPath

#838 Add Nextdoor taboo & Familycreep to Gamma
  SCRAPERS-LIST.md
  scrapers/GammaEntertainment.yml
  scrapers/StagCollective.yml
Labels: enhancement

#852 Add sceneSearch to IWantClips scraper
  SCRAPERS-LIST.md
  scrapers/IWantClips.yml
Labels: enhancement, CDP

#845 Fix Helix Studios Title
  scrapers/HelixStudios.yml
Labels: enhancement, xPath

#850 Himeros fix
  scrapers/HimerosTV.yml
Labels: enhancement, fix

#840 Sayuncle.com
  SCRAPERS-LIST.md
  scrapers/Sayuncle.yml
Labels: xPath

#841 Add Frenchtwinks
  SCRAPERS-LIST.md
  scrapers/Frenchtwinks.yml
Labels: xPath

#843 Add Fuckermate
  SCRAPERS-LIST.md
  scrapers/Fuckermate.yml
Labels: xPath

#844 Add Masqulin
  SCRAPERS-LIST.md
  scrapers/Masqulin.yml
Labels: xPath

#856 Add UltraFilms
  SCRAPERS-LIST.md
  scrapers/UltraFilms.yml
Labels: xPath

#851 Add Thicc18 support to Fit18 scraper
  SCRAPERS-LIST.md
  scrapers/Fit18.py
  scrapers/Fit18.yml
Labels: script

#831 Add ZexyVR
  SCRAPERS-LIST.md
  scrapers/ZexyVR.yml
Labels: xPath

#849 Fix vixenNetwork scraper
  scrapers/vixenNetwork.py
  scrapers/vixenNetwork.yml
Labels: script, fix

#854 Add WAPdB python scraper
  SCRAPERS-LIST.md
  scrapers/WAPdB.py
  scrapers/WAPdB.yml
Labels: script

#863 Fix R18 search in JavLibrary_python fragment scraper
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: fix

#860 add DarkRoomVR scraper for scenes
  SCRAPERS-LIST.md
  scrapers/DarkRoomVR.yml
Labels: xPath

#862 Update WilliamHiggins (Add more sites)
  SCRAPERS-LIST.md
  scrapers/Williamhiggins.yml
Labels: enhancement, xPath

#847 Adding an onlyfans scraper using the DIGITALCRIMINAL onlyfans tool
  scrapers/dc-onlyfans.py
  scrapers/dc-onlyfans.yml
Labels: script

#865 create Tripforfuck
  SCRAPERS-LIST.md
  scrapers/TripForFuck.yml
Labels: xPath

#855 Add GotFilled
  SCRAPERS-LIST.md
  scrapers/KBProductions.py
  scrapers/KBProductions.yml
Labels: xPath

#853 Update IFeelMyself.py
  scrapers/IFeelMyself.py
  scrapers/IFeelMyself.yml
Labels: enhancement, script

#871 Add AnimeCharactersDatabase
  SCRAPERS-LIST.md
  scrapers/AnimeCharactersDatabase.py
  scrapers/AnimeCharactersDatabase.yml
Labels: script

#878 Update manyvids scraper to fix titles not coming through
  scrapers/ManyVids.yml
Labels: fix

#875 Update Kink, switch to CDP
  SCRAPERS-LIST.md
  scrapers/Kink.yml
Labels: fix, CDP

#872 Added addicted2girls python scene scraper, fixed 21sextreme
  SCRAPERS-LIST.md
  scrapers/Algolia.py
  scrapers/Algolia_21Naturals.yml
  scrapers/Algolia_21Sextreme.yml
  scrapers/Algolia_21Sextury.yml
  scrapers/Algolia_AddictedToGirls.yml
  scrapers/Algolia_AllGirlMassage.yml
  scrapers/Algolia_Biphoria.yml
  scrapers/Algolia_BurningAngel.yml
  scrapers/Algolia_ClubInfernoDungeon.yml
  scrapers/Algolia_DevilsFilm.yml
  scrapers/Algolia_FantasyMassage.yml
  scrapers/Algolia_Girlsway.yml
  scrapers/Algolia_PureTaboo.yml
  scrapers/Algolia_RoccoSiffredi.yml
  scrapers/GammaEntertainment.yml
  scrapers/PureTaboo.yml
Labels: script, fix

#880 Fix image pp in ATKExotics scaper
  scrapers/ATKExotics.yml
Labels: fix, CDP

#861 PornstarPlatinum scraper (Xpath)
  SCRAPERS-LIST.md
  scrapers/PornstarPlatinum.yml
Labels: xPath

#885 Add perfectgirlfriend.com to FamilyTherapyXXX
  SCRAPERS-LIST.md
  scrapers/FamilyTherapyXXX.yml
Labels: enhancement

#881 Fix tags pp in MindGeek scraper
  scrapers/MindGeek.yml
Labels: fix

#888 Add more banned words to JavLibrary_python
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: enhancement, script

#886 Fix JacquieEtMichelTV scraper
  scrapers/JacquieEtMichelTV.py
  scrapers/JacquieEtMichelTV.yml
Labels: script, fix
