Repository stashapp/CommunityScrapers, pull requests merged in 2022-03, with the labels that each got.

#922 Add MyCherryCrush XPath Scene Scraper
  SCRAPERS-LIST.md
  scrapers/MyCherryCrush.yml
Labels: xPath, CDP

#935 Add scraper for crashpadseries.com
  SCRAPERS-LIST.md
  scrapers/CrashpadSeries.yml
Labels: xPath

#926 Use cloudscraper for Teamskeet
  scrapers/Teamskeet.yml
  scrapers/TeamskeetAPI.py
Labels: script, fix

#929 Add TwoTGirls xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/TwoTGirls.yml
Labels: xPath

#932 Fix excogi details (ExploitedX.yml)
  scrapers/ExploitedX.yml
Labels: fix

#933 Fix performer names for Nympho.yml
  scrapers/Nympho.yml
Labels: fix

#934 Fix ArchAngelVideo.yml
  scrapers/ArchAngelVideo.yml
Labels: fix

#938 add series name as studio name (CherryPimps.yml)
  scrapers/CherryPimps.yml
Labels: enhancement

#937 add DollsHub
  SCRAPERS-LIST.md
  scrapers/DollsHub.yml
Labels: xPath

#939 add fragileslave.com url scraper
  SCRAPERS-LIST.md
  scrapers/FragileSlave.yml
Labels: xPath

#940 Create PinkVisual.yml
  SCRAPERS-LIST.md
  scrapers/PinkVisual.yml
Labels: xPath

#943 Update IFeelMyself.py
  scrapers/IFeelMyself.py
  scrapers/IFeelMyself.yml
Labels: script, fix

#944 Add EastBoys Scraper
  SCRAPERS-LIST.md
  scrapers/EastBoys.yml
Labels: xPath

#951 Fix xbvrdb date parsing
  scrapers/xbvrdb.py
  scrapers/xbvrdb.yml
Labels: script, fix

#949 add Zentai Dolls
  SCRAPERS-LIST.md
  scrapers/ZentaiDolls.yml
Labels: xPath

#954 Update SexLikeReal.yml
  scrapers/SexLikeReal.yml
Labels: fix

#956 Fix Wankitnow details
  SCRAPERS-LIST.md
  scrapers/Wankitnow.yml
  scrapers/wankitnow.yml
Labels: fix

#955 Add Mature.nl
  SCRAPERS-LIST.md
  scrapers/MatureNL.yml
Labels: xPath

#958 Add inserted.com
  SCRAPERS-LIST.md
  scrapers/KBProductions.yml
Labels: enhancement, script

#961 Add WillTileXXX
  SCRAPERS-LIST.md
  scrapers/KBProductions.yml
  scrapers/WillTileXXX.yml
Labels: xPath

#963 Update tag and performer parsing for VNAGirls site
  scrapers/VNAGirls.yml
Labels: xPath, fix

#964 AMAMultimedia (add facials4k.com)
  SCRAPERS-LIST.md
  scrapers/AMAMultimedia.yml
Labels: enhancement, xPath

#960 Update data18 scraper (fixes)
  scrapers/data18.yml
Labels: xPath, fix

#959 Add movie support for IMDB scraper
  SCRAPERS-LIST.md
  scrapers/IMDB.yml
Labels: enhancement, xPath

#962 Add option to scrape all performers in Algolia API scenes, not just females
  scrapers/Algolia.py
  scrapers/Algolia_21Naturals.yml
  scrapers/Algolia_21Sextreme.yml
  scrapers/Algolia_21Sextury.yml
  scrapers/Algolia_AddictedToGirls.yml
  scrapers/Algolia_Adultime.yml
  scrapers/Algolia_AllGirlMassage.yml
  scrapers/Algolia_Biphoria.yml
  scrapers/Algolia_BurningAngel.yml
  scrapers/Algolia_ClubInfernoDungeon.yml
  scrapers/Algolia_DevilsFilm.yml
  scrapers/Algolia_FantasyMassage.yml
  scrapers/Algolia_Girlsway.yml
  scrapers/Algolia_PureTaboo.yml
  scrapers/Algolia_RoccoSiffredi.yml
  scrapers/Algolia_disruptivefilms.yml
  scrapers/Algolia_filthykings.yml
  scrapers/Algolia_mypervyfamily.yml
  scrapers/Algolia_touchmywife.yml
  scrapers/Algolia_zerotolerancefilms.yml
Labels: enhancement, script
