Repository stashapp/CommunityScrapers, pull requests merged in 2022-05, with the labels that each got.

#986 add sceneByFragment to LoveHerFeet
  scrapers/LoveHerFeet.yml
Labels: enhancement

#977 add grooby.club scraper
  SCRAPERS-LIST.md
  scrapers/GroobyClub.yml
Labels: xPath

#985 Add performer scrapers for Kpopping
  SCRAPERS-LIST.md
  scrapers/Kpopping.yml
Labels: xPath

#984 Strip commas from tags
  scrapers/RealityKingsOL.yml
Labels: fix

#991 Fix plumberpass
  scrapers/PlumperPass.yml
Labels: fix

#988 HQPorner
  SCRAPERS-LIST.md
  scrapers/HQPorner.yml
Labels: xPath

#990 Update javlibrary mirrors for javlibrary_python scraper
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: script, fix

#997 Updating Image selector for NaughtyAmericaVR
  scrapers/NaughtyAmericaVR.yml
Labels: fix

#995 Add xPath scraper for japornxxx.com
  SCRAPERS-LIST.md
  scrapers/JapornXXX.yml
Labels: xPath

#996 Add EricVideos xPath scene, performer scraper
  SCRAPERS-LIST.md
  scrapers/EricVideos.yml
Labels: xPath

#1000 Add ShinyBound xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/ShinyBound.yml
Labels: xPath
