Repository stashapp/CommunityScrapers, pull requests merged in 2022-10, with the labels that each got.

#1155 Update AdultPrime.yml
  scrapers/AdultPrime.yml
Labels: enhancement, xPath

#1151 Add movie support for ThePorndb
  SCRAPERS-LIST.md
  scrapers/ThePornDB.yml
Labels: enhancement, JSON

#1154 Update ThirdSexXXX.yml
  scrapers/ThirdSexXXX.yml
Labels: xPath, fix

#1146 WoodmancastingX scraper
  SCRAPERS-LIST.md
  scrapers/WoodmancastingX.yml
Labels: xPath

#1135 venus WowNetwork scraper
  SCRAPERS-LIST.md
  scrapers/WowNetworkVenus/WowNetworkVenus.py
  scrapers/WowNetworkVenus/WowNetworkVenus.yml
  scrapers/WowNetworkVenus/requirements.txt
Labels: script

#1157 Fix Bang scraper
  scrapers/Bang.yml
Labels: xPath, fix, CDP

#1158 Fix Reality Kings scraping
  SCRAPERS-LIST.md
  scrapers/MindGeek.yml
Labels: fix

#1150 scrape scene date/cover/studio from milovana forum release posts
  SCRAPERS-LIST.md
  scrapers/Milovana.yml
Labels: xPath

#1147 Scraper for assumethepositionstudios.com
  SCRAPERS-LIST.md
  scrapers/AssumeThePositionStudios.yml
Labels: xPath

#1160 Fix JavHD scraper
  scrapers/JavHD.yml
Labels: fix
