Repository stashapp/CommunityScrapers, pull requests merged in 2022-02, with the labels that each got.

#891 Add activeduty as supported performer Url to GammaEntertainment.yml
  SCRAPERS-LIST.md
  scrapers/GammaEntertainment.yml
Labels: enhancement, xPath

#892 Add AdultFilmIndex parser
  SCRAPERS-LIST.md
  scrapers/AdultFilmIndex.yml
Labels: JSON

#893 Add Domai and GoddessNudes support
  SCRAPERS-LIST.md
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
Labels: enhancement, fix

#890 Add Boobpedia xPath performer scraper
  SCRAPERS-LIST.md
  scrapers/Boobpedia.yml
Labels: xPath

#894 Fix AdultFilmIndex direct scene urls
  scrapers/AdultFilmIndex.yml
Labels: fix

#884 Fix performer/bio URL for TheNude scraper
  scrapers/TheNude.yml
Labels: fix

#896 Add performer support to CorbinFisher scraper
  SCRAPERS-LIST.md
  scrapers/CorbinFisher.yml
Labels: enhancement, xPath

#895 Scrapper to copy scene data to gallery
  SCRAPERS-LIST.md
  scrapers/CopyToGallery.py
  scrapers/CopyToGallery.yml
Labels: script

#899 Fix issue with missing scene covers in SARJ scraper
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
Labels: enhancement

#887 add Pissplay
  SCRAPERS-LIST.md
  scrapers/PissPlay.yml
Labels: xPath

#902 Add SexMex xPath scene and gallery scraper
  SCRAPERS-LIST.md
  scrapers/SexMex.yml
Labels: xPath

#905 [XPath] Update javdb.yml (URL)
  SCRAPERS-LIST.md
  scrapers/javdb.yml
Labels: fix

#911 Fix tags for MindGeek.yml
  scrapers/MindGeek.yml
Labels: fix

#908 Fix kinkyfamily image
  scrapers/kinkyfamily.yml
Labels: fix

#907 Adding performer scraping in Cospuri.com
  SCRAPERS-LIST.md
  scrapers/Cospuri.yml
Labels: enhancement

#903 add VirtualPee
  SCRAPERS-LIST.md
  scrapers/VirtualPee.yml
Labels: xPath

#909 Scene support for TeasePOV
  SCRAPERS-LIST.md
  scrapers/TeasePOV.yml
Labels: xPath

#913 Add Killergram xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/Killergram.yml
Labels: xPath

#921 changed dc-onlyfans for all possible media types
  scrapers/dc-onlyfans.py
  scrapers/dc-onlyfans.yml
Labels: enhancement

#923 Add TinySis to PaperStreetMedia.yml
  SCRAPERS-LIST.md
  scrapers/PaperStreetMedia.yml
Labels: xPath

#919 Add JavHub xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/JavHub.yml
Labels: xPath
