Repository stashapp/CommunityScrapers, pull requests merged in 2022-04, with the labels that each got.

#967 Update Hegre.yml
  scrapers/Hegre.yml
Labels: fix

#969 Add BradMontana.com scraper
  SCRAPERS-LIST.md
  scrapers/BradMontana.yml
Labels: xPath

#970 Add xSinsVR scraper
  SCRAPERS-LIST.md
  scrapers/xSinsVR.yml
Labels: xPath

#971 Fix studio selector for AdultEmpireCash
  scrapers/AdultEmpireCash.yml
Labels: fix

#973 Updated ScrapeWithUrl to return a URL value as well for people scraping from archive.org
  scrapers/ScrapeWithURL.py
  scrapers/ScrapeWithURL.yml
Labels: enhancement

#972 create Vrxdb
  SCRAPERS-LIST.md
  scrapers/VrxDB.yml
Labels: xPath

#978 [dc-onlyfans] use log module for logging
  scrapers/dc-onlyfans.py
  scrapers/dc-onlyfans.yml
Labels: enhancement, script
