Repository stashapp/CommunityScrapers, pull requests merged in 2022-06, with the labels that each got.

#1002 Fix MenAtPlay scraper
  scrapers/MenAtPlay.yml
Labels: xPath, fix

#1009 Update javdb.yml
  scrapers/javdb.yml
Labels: fix

#1004 Update ThirdRockEnt.yml
  SCRAPERS-LIST.md
  scrapers/ThirdRockEnt.yml
Labels: xPath

#1006 Update iFeelMyself.py
  scrapers/IFeelMyself.py
  scrapers/IFeelMyself.yml
Labels: enhancement, script

#1007 Add It's POV scene scraper
  SCRAPERS-LIST.md
  scrapers/ItsPOV.yml
Labels: CDP

#1010 [IAFD] use py_common.log for logging
  scrapers/IAFD.py
  scrapers/IAFD.yml
Labels: enhancement, script

#1023 [Python] update MindGeekAPI to use log.py
  scrapers/MindGeekAPI.py
  scrapers/MindGeekAPI.yml
Labels: enhancement, script

#1025 [UltraFilms] Fix title and studio
  scrapers/UltraFilms.yml
Labels: fix

#1017 Update ExploitedX.yml
  SCRAPERS-LIST.md
  scrapers/Backroomcastingcouch.yml
  scrapers/ExploitedX.yml
Labels: enhancement

#1020 Update Wankitnow.yml
  scrapers/Wankitnow.yml
Labels: enhancement

#1011 Use py_common and apply some pylint fixes for JavLibrary_python
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: enhancement, script

#1024 [Hegre] Fix scene URL
  scrapers/Hegre.yml
Labels: enhancement, fix

#992 Add dlsite scraper
  SCRAPERS-LIST.md
  scrapers/DLsite.yml
Labels: xPath

#1021 [TheFlourishXXX] Add scene scraper
  SCRAPERS-LIST.md
  scrapers/TheFlourish.yml
Labels: xPath

#1019 [AdultPrime] add basic scraping for AP
  SCRAPERS-LIST.md
  scrapers/AdultPrime.yml
Labels: xPath

#1045 xHamster: fix studio, tags and performers extracting
  scrapers/Xhamster.yml
Labels: fix

#1033 wakeupnfuck.com xPath scraper
  SCRAPERS-LIST.md
  scrapers/WakeUpnFuck.yml
Labels: xPath

#1022 [ModelMediaUS] adding an alt scraper that works with jerkaoke, delphinefilms and mmasia
  SCRAPERS-LIST.md
  scrapers/ModelMediaUS.yml
Labels: enhancement

#1044 Add LustCinema scrapper
  SCRAPERS-LIST.md
  scrapers/LustCinema.yml
Labels: xPath

#1031 Update Straplez as being now part of SARJ
  SCRAPERS-LIST.md
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
  scrapers/Straplezz.yml
Labels: script, fix

#1046 Add Futanari.xxx scrapper
  SCRAPERS-LIST.md
  scrapers/Hentaied.yml
Labels: enhancement

#1043 freshmen.net xPath scraper
  SCRAPERS-LIST.md
  scrapers/Freshmen.yml
Labels: xPath

#1042 blakemason.com xPath scraper
  SCRAPERS-LIST.md
  scrapers/BlakeMason.yml
Labels: xPath
