Repository stashapp/CommunityScrapers, pull requests merged in 2022-09, with the labels that each got.

#1119 Create TakeVan
  SCRAPERS-LIST.md
  scrapers/TakeVan.yml
Labels: xPath

#1123 Comment update for py_common > config.py
  scrapers/py_common/config.py
Labels: documentation

#1127 BondageCafe xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/BondageCafe.yml
Labels: xPath

#1129 BrandNewAmateurs xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/BrandNewAmateurs.yml
Labels: xPath

#1128 JimWeathersArchives xPath scene/performer scraper
  SCRAPERS-LIST.md
  scrapers/JimWeathersArchives.yml
Labels: xPath

#1126 AmateureExtreme xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/AmateureExtreme.yml
Labels: xPath

#1125 New MissaX/AllHerLuv scraper
  SCRAPERS-LIST.md
  scrapers/AllHerLuv.yml
  scrapers/MissaX.py
  scrapers/MissaX.yml
Labels: script

#1130 Add MySweetApple xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/MySweetApple.yml
Labels: xPath

#1117 Move Adult Time sites to Algolia_Adultime.yml
  SCRAPERS-LIST.md
  scrapers/Algolia_Adultime.yml
  scrapers/Algolia_MenOver30.yml
  scrapers/GammaEntertainment.yml
  scrapers/Mypervmom.yml
Labels: enhancement

#1131 Fix incorrect link on README.md
  README.md
Labels: documentation, fix

#1074 initial implementation of rb_common
  scrapers/rb_common/README.md
  scrapers/rb_common/configs/README.md
  scrapers/rb_common/configs/config_base.rb
  scrapers/rb_common/configs/stash_config.rb
  scrapers/rb_common/configs/stashdb_config.rb
  scrapers/rb_common/graphql/README.md
  scrapers/rb_common/graphql/graphql_base.rb
  scrapers/rb_common/graphql/stash.rb
  scrapers/rb_common/logger.rb
  scrapers/rb_common/rb_common.rb
Labels: script

#1084 Move EvilAngel, Wicked, Diabolic to Algolia
  SCRAPERS-LIST.md
  scrapers/Algolia.py
  scrapers/Algolia_EvilAngel.yml
  scrapers/Algolia_Wicked.yml
  scrapers/Algolia_zerotolerancefilms.yml
  scrapers/Diabolic.yml
  scrapers/GammaEntertainment.yml
Labels: enhancement, script, fix

#1132 Use full image for ThePornDB scraper
  scrapers/ThePornDB.yml
Labels: enhancement

#1137 ThePornDB.yml add queryURLReplace
  SCRAPERS-LIST.md
  scrapers/PornDB.yml
  scrapers/ThePornDB.yml
Labels: JSON

#1122 WowGirls Blog and MMP Network added
  SCRAPERS-LIST.md
  scrapers/MMP_Network.yml
  scrapers/WOWGirlsBlog.yml
Labels: xPath

#1134 Fix BJRaw/Gotfilled/KBP scrapers
  SCRAPERS-LIST.md
  scrapers/BJRaw.yml
  scrapers/KBProductions.yml
Labels: script, fix, CDP

#1136 Scrape filename to scene title
  SCRAPERS-LIST.md
  scrapers/Filename.py
  scrapers/Filename.yml
Labels: script

#1118 Update SexLikeReal.yml
  scrapers/SexLikeReal.yml
Labels: fix

#1039 feat: Performer Image by scene cover scraper
  SCRAPERS-LIST.md
  scrapers/performer-image-by-scene.py
  scrapers/performer-image-by-scene.yml
  scrapers/py_common/graphql.py
Labels: script

#1141 Use algolia api scraper for joymii
  SCRAPERS-LIST.md
  scrapers/Algolia_Adultime.yml
  scrapers/joymii.yml
Labels: script, fix

#1144 BugFix PornCZ: Fixed image URL and added release date
  SCRAPERS-LIST.md
  scrapers/Porncz.yml
Labels: fix
