Repository stashapp/CommunityScrapers, pull requests merged in 2022-12, with the labels that each got.

#1168 new FFD scraper
  SCRAPERS-LIST.md
  scrapers/FootFetishDaily.yml
Labels: xPath

#1185 Add director for SARJ-LLC scraper, minor tweaks fixes
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
Labels: enhancement

#1190 Add Studio Code and Director (and some more) to JavLibrary_python
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: enhancement

#1195 Update Algolia Adulttime (add more sites)
  SCRAPERS-LIST.md
  scrapers/Algolia_Adultime.yml
  scrapers/GammaEntertainment.yml
Labels: enhancement

#1189 Fix GammaEntertainment movie cropped images
  scrapers/Algolia.py
Labels: fix

#1184 Add scrapping by official filename to a few scrappers
  scrapers/BaDoink.yml
  scrapers/SexLikeReal.yml
  scrapers/VRBangers.yml
  scrapers/VirtualRealPorn.yml
Labels: enhancement

#1197 JavLibrary_python: replace some obfuscated tags
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: enhancement

#1194 Add scene scraper for hmvmania.com
  SCRAPERS-LIST.md
  scrapers/HmvMania.yml
Labels: xPath

#1210 map all Kink sub-studios
  scrapers/Kink.yml
Labels: enhancement, xPath

#1196 Add Rule34Video xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/Rule34Video.yml
Labels: xPath

#1199 Update Xhamster.yml
  scrapers/Xhamster.yml
Labels: enhancement

#1205 Update Code selector for LegalPorno.yml
  scrapers/LegalPorno.yml
Labels: enhancement, xPath

#1212 add analtherapyxxx.com
  SCRAPERS-LIST.md
  scrapers/FamilyTherapyXXX.yml
Labels: enhancement, xPath

#1139 Added xPath scraper for bondageliberation.com
  SCRAPERS-LIST.md
  scrapers/BondageLiberation.yml
Labels: xPath

#1219 Improve sexlikereal
  scrapers/SexLikeReal.yml
Labels: enhancement

#1207 add pansexualx.com and transgressivexxx.com to Algolia_EvilAngel
  SCRAPERS-LIST.md
  scrapers/Algolia_EvilAngel.yml
Labels: enhancement, script

#1228 Add scraper for smashed.xxx
  SCRAPERS-LIST.md
  scrapers/Nubiles.yml
Labels: xPath

#1202 Update DreamTranny.yml
  scrapers/DreamTranny.yml
Labels: xPath, fix
