Repository stashapp/CommunityScrapers, pull requests merged in 2022-07, with the labels that each got.

#1049 Update NaughtyAmerica.yml
  scrapers/NaughtyAmerica.yml
Labels: fix

#1040 improve groobyclub, purets image selectors
  SCRAPERS-LIST.md
  scrapers/ChristianXXX.yml
  scrapers/GroobyClub.yml
Labels: enhancement

#1037 Add scraper for ChaosMen.com
  SCRAPERS-LIST.md
  scrapers/ChaosMen.yml
Labels: xPath

#1029 Add xPath scraper for Jeedoo.com
  SCRAPERS-LIST.md
  scrapers/Jeedoo.yml
Labels: xPath

#1018 [Bang.com] add movie and performer scraper
  .gitignore
  SCRAPERS-LIST.md
  scrapers/Bang.yml
Labels: enhancement

#1048 Tweak data18 movie duration selector/pp
  scrapers/data18.yml
Labels: enhancement

#1016 Scraper for FratX.com
  SCRAPERS-LIST.md
  scrapers/FratX.py
  scrapers/FratX.yml
Labels: script

#1052 Pornhub fix
  scrapers/Pornhub.yml
Labels: fix

#1053 Minor fix to get the cover image on Manyvids
  scrapers/ManyVids.yml
Labels: fix

#1038 AEBN xPath performer scraper
  SCRAPERS-LIST.md
  scrapers/AEBN.yml
Labels: enhancement

#1059 Add mapping for FOH in NSNS scraper
  scrapers/NewSensationsNetworkSites.yml
Labels: fix

#1058 [Pornditos] get better image from scrape
  SCRAPERS-LIST.md
  scrapers/Pornditos.yml
Labels: enhancement

#1060 [Javlibrary python] fix image using search
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: fix

#1050 Add hypnotube.com xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/Hypnotube.yml
Labels: xPath

#1056 Pornhub - scrape description when available
  scrapers/Pornhub.yml
Labels: enhancement

#1063 Updated StasyQ works for Scenes and Performer scraping
  scrapers/StasyQ.yml
Labels: fix

#1065 Add Johnny Rapid
  SCRAPERS-LIST.md
  scrapers/Algolia_Johnnyrapid.yml
Labels: script

#1066 ensure descriptions keep their paragraph structure
  scrapers/ManyVids.yml
Labels: enhancement

#1047 LHF images for BTS + new URL
  SCRAPERS-LIST.md
  scrapers/LoveHerFeet.yml
Labels: enhancement, fix

#1057 [dc-onlyfans] Add gallery scraping
  scrapers/dc-onlyfans.py
  scrapers/dc-onlyfans.yml
Labels: enhancement

#1061 add scraper for pinklabel.tv
  SCRAPERS-LIST.md
  scrapers/PinkLabelTV.yml
Labels: xPath

#1076 Add xpath scraper for povadventure.com
  SCRAPERS-LIST.md
  scrapers/ModelMediaUS.yml
Labels: xPath

#1080 Update Penthouse.yml
  scrapers/Penthouse.yml
Labels: enhancement

#1064 Clone of AdultEmpire, for the gay version of site
  SCRAPERS-LIST.md
  scrapers/GayAdultEmpire.yml
Labels: xPath

#1067 Iwantclips performers
  SCRAPERS-LIST.md
  scrapers/IWantClips.yml
Labels: enhancement
