Repository stashapp/CommunityScrapers, pull requests merged in 2022-08, with the labels that each got.

#1081 Update MeanaWolf.yml
  scrapers/MeanaWolf.yml
Labels: fix

#1070 Add Xevunleashed
  SCRAPERS-LIST.md
  scrapers/Xevunleashed.yml
Labels: xPath

#1069 Switch to a python scraper for ManyVids
  SCRAPERS-LIST.md
  scrapers/ManyVids.yml
  scrapers/ManyVids/ManyVids.py
  scrapers/ManyVids/ManyVids.yml
  scrapers/ManyVids/README.md
  scrapers/ManyVids/requirements.txt
Labels: script

#1087 Hotandtatted
  SCRAPERS-LIST.md
  scrapers/hussiemodels.yml
Labels: xPath

#1082 add Club elegant angel
  SCRAPERS-LIST.md
  scrapers/ClubElegantAngel.yml
Labels: xPath

#1092 ManyVids - Tweak id_match
  scrapers/ManyVids/ManyVids.py
  scrapers/ManyVids/ManyVids.yml
Labels: enhancement, script

#968 Shoko api
  scrapers/ShokoAPI.py
  scrapers/ShokoAPI/ShokoAPI.py
  scrapers/ShokoAPI/ShokoAPI.yml
Labels: enhancement, script

#1014 new scraper for sexselector.com & twistys.com, update multiple scrapers
  SCRAPERS-LIST.md
  scrapers/Algolia_Adultime.yml
  scrapers/Algolia_TabooHeat.yml
  scrapers/Algolia_xEmpire.yml
  scrapers/BangBros.yml
  scrapers/Brazzers.yml
  scrapers/DogFart.yml
  scrapers/DorcelClub.yml
  scrapers/FreakMobMedia.yml
  scrapers/GammaEntertainment.yml
  scrapers/JulesJordan.yml
  scrapers/MindGeek.yml
  scrapers/Mylf.yml
  scrapers/Nympho.yml
  scrapers/PaperStreetMedia.yml
  scrapers/ProducersFun.yml
  scrapers/RealityKingsOL.yml
  scrapers/SexSelector.yml
  scrapers/TabooHeat.yml
  scrapers/ThirdRockEnt.yml
  scrapers/Twistys.yml
  scrapers/hussiemodels.yml
  scrapers/purgatoryx.yml
  scrapers/trafficpimps.yml
Labels: xPath

#1093 Correctly handle missing scene/movie dates for IAFD scraper
  scrapers/IAFD.py
  scrapers/IAFD.yml
Labels: script, fix

#1090 [YML] Create Putalocura scraper
  SCRAPERS-LIST.md
  scrapers/Putalocura.yml
Labels: xPath

#1085 change title and add performer url Cospuri.yml
  scrapers/Cospuri.yml
Labels: enhancement, xPath

#1071 Add search to Clips4sale
  scrapers/Clips4Sale.yml
Labels: enhancement, xPath

#1100 Virtualtaboo Fix studio name not beeing scraped
  scrapers/VirtualTaboo.yml
Labels: fix

#1101 SexbabesVR scraper - fix date, desc ,studio
  scrapers/SexBabesVR.yml
Labels: fix

#1102 Update virtualrealporn network scraper
  SCRAPERS-LIST.md
  scrapers/VirtualRealPorn.yml
Labels: fix

#1104 Update VRBangers.yml
  SCRAPERS-LIST.md
  scrapers/VRBangers.yml
  scrapers/VRConk.yml
Labels: fix

#1086 tagger and scene url changes Theporndb.yml
  scrapers/ThePornDB.yml
Labels: enhancement, JSON

#1097 Hotmovies - small tweak
  scrapers/Hotmovies.yml
Labels: enhancement

#1111 tagger change for JavLibrary Python
  scrapers/JavLibrary_python.py
  scrapers/JavLibrary_python.yml
Labels: enhancement, script

#1109 LetsDoeIt scraper fixes
  scrapers/LetsDoeIt.yml
Labels: fix

#1112 fix clips4sale images
  scrapers/Clips4Sale.yml
Labels: fix

#1096 IMDB small tweaks
  scrapers/IMDB.yml
Labels: enhancement

#1105 New Elite babes scraper
  SCRAPERS-LIST.md
  scrapers/EliteBabes.yml
Labels: xPath

#1108 theNude scraper fixes
  scrapers/TheNude.yml
Labels: fix

#1113 Taratainton.com and xes.pl scene scrappers
  SCRAPERS-LIST.md
  scrapers/TaraTainton.yml
  scrapers/Xes.yml
Labels: xPath

#1083 LHF: performer search/scrape
  SCRAPERS-LIST.md
  scrapers/LoveHerFeet.yml
Labels: enhancement
