Repository stashapp/CommunityScrapers, pull requests merged in 2022-11, with the labels that each got.

#1161 Add MrBigFatDick. Fix SexLikeReal description for some scenes.
  SCRAPERS-LIST.md
  scrapers/MrBigFatDick.yml
  scrapers/SexLikeReal.yml
Labels: enhancement, fix

#1176 Update graphql.py
  scrapers/py_common/graphql.py
Labels: script, fix

#1165 Add xVirtual scrapper
  SCRAPERS-LIST.md
  scrapers/XVirtual.yml
Labels: xPath

#1163 [Hegre] Add search for tagger view
  scrapers/Hegre.yml
Labels: enhancement

#1169 Switch to an Algolia API scraper for GangbangCreampie
  SCRAPERS-LIST.md
  scrapers/Algolia_GangBangCreampie.yml
  scrapers/Aziani.yml
Labels: script

#1170 remove CDP req for Bang scraper
  SCRAPERS-LIST.md
  scrapers/Bang.yml
Labels: enhancement, fix

#1173 Add more sites to Only3xGirls scraper
  SCRAPERS-LIST.md
  scrapers/Only3xGirls.yml
Labels: xPath

#1171 Add more sites to Mypervmom
  SCRAPERS-LIST.md
  scrapers/Mypervmom.yml
Labels: xPath

#1178 Add Scene studio code, director to validator schema
  validator/scraper.schema.json
Labels: utility

#1164 [AdultPrime] Add search
  scrapers/AdultPrime.yml
Labels: enhancement

#1162 updated ifeelmyself scraper to include performer scraper and fix some issues with scene scraper
  SCRAPERS-LIST.md
  scrapers/IFeelMyself.py
  scrapers/IFeelMyself.yml
Labels: enhancement, script

#1166 Add date to SpankBank
  scrapers/SpankBang.yml
Labels: enhancement

#1167 Adding PMV creator NoodleDude's website
  SCRAPERS-LIST.md
  scrapers/Noodledude.yml
Labels: xPath

#1181 Update xHamster scraper
  scrapers/Xhamster.yml
Labels: enhancement

#1174 Add scene scraper for cockhero.info
  SCRAPERS-LIST.md
  scrapers/Cockhero.yml
Labels: xPath

#1180 Update SpankBang scraper
  scrapers/SpankBang.yml
Labels: xPath, fix

#1175 milovana: added scene by Name and QueryFragment and retrieve title
  scrapers/Milovana.yml
Labels: enhancement, xPath
