Repository stashapp/CommunityScrapers, pull requests merged in 2023-01, with the labels that each got.

#1229 Use higher res scene cover for ManyVids
  scrapers/ManyVids/ManyVids.py
  scrapers/ManyVids/ManyVids.yml
Labels: enhancement, script

#1224 Use 1920x1080 for image resize in GammaEntertainment
  scrapers/GammaEntertainment.yml
Labels: enhancement, xPath

#1068 Meanbitches scraper
  SCRAPERS-LIST.md
  scrapers/MeanBitches.yml
Labels: xPath

#1220 Fix selector to grab scenes from stickydollar network and add dirtyauditions site
  SCRAPERS-LIST.md
  scrapers/Nympho.yml
Labels: enhancement, xPath

#1208 add czechvrnetwork.com
  SCRAPERS-LIST.md
  scrapers/CzechVR.yml
Labels: enhancement, xPath

#1227 Fix KBProductions Parsing and Start Parsing Ricky's Room
  SCRAPERS-LIST.md
  scrapers/KBProductions.py
  scrapers/KBProductions.yml
Labels: script, fix

#1223 Add xPath scene scraper ColbyKnox.yml
  SCRAPERS-LIST.md
  scrapers/ColbyKnox.yml
Labels: xPath

#1209 add brazilian-transsexuals.com and braziltgirls.xxx
  SCRAPERS-LIST.md
  scrapers/GroobyNetwork-Brazilian.yml
Labels: xPath

#1215 add pinkotgirls.com
  SCRAPERS-LIST.md
  scrapers/Pinkoclub.yml
Labels: enhancement

#1232 add porkvendors.com to ThirdRockEnt.yml & smutfactor.com to AdultEmpireCash.yml
  SCRAPERS-LIST.md
  scrapers/AdultEmpireCash.yml
  scrapers/ThirdRockEnt.yml
Labels: enhancement, xPath

#1221 Update KristenBjorn.yml
  scrapers/KristenBjorn.yml
Labels: enhancement, xPath, fix

#1222 Update Staxus.yml
  scrapers/Staxus.yml
Labels: enhancement, xPath, fix

#1238 Update LucasEntertainment.yml
  scrapers/LucasEntertainment.yml
Labels: enhancement

#1237 Improve dreamtranny
  scrapers/DreamTranny.yml
Labels: enhancement

#864 Updating CopyFromScene to use py_common libraries.
  SCRAPERS-LIST.md
  scrapers/CopyFromScene.py
  scrapers/CopyFromScene.yml
Labels: enhancement, script

#1241 Move broken Chaosmen scraper to algolia
  SCRAPERS-LIST.md
  scrapers/Algolia.py
  scrapers/Algolia_ChaosMen.yml
  scrapers/ChaosMen.yml
Labels: script, fix

#1235 Fix CruelGirlfriend scraper
  scrapers/CruelGirlfriend.yml
Labels: xPath, fix

#1239 Update Masqulin.yml
  scrapers/Masqulin.yml
Labels: xPath, fix

#1226 Update MindGeek.yml (add Noirmale.com)
  SCRAPERS-LIST.md
  scrapers/MindGeek.yml
Labels: xPath

#1211 Add scraper for Breed It Raw
  SCRAPERS-LIST.md
  scrapers/BreedItRaw.yml
Labels: xPath

#1242 move tsplayground.com to its own scraper
  SCRAPERS-LIST.md
  scrapers/GammaEntertainment.yml
  scrapers/TSPlayground.yml
Labels: xPath, fix

#1243 Update class names of Lustery
  scrapers/Lustery.yml
Labels: enhancement, fix

#1230 Revision of Boobpedia scraper
  scrapers/Boobpedia.yml
Labels: enhancement, fix

#1246 Add JSON scraper for riggsfilms.vip
  SCRAPERS-LIST.md
  scrapers/RiggsFilms.yml
Labels: JSON

#1244 Add scraper for R18.dev
  SCRAPERS-LIST.md
  scrapers/R18.dev.yml
Labels: JSON

#1251 Update Hypnotube.yml to pull in main video thumbnail
  scrapers/Hypnotube.yml
Labels: fix

#1250 Fix xvideos scene scraper
  scrapers/Xvideos.yml
Labels: fix

#1253 Fetch all tags from Mature.nl
  scrapers/MatureNL.yml
Labels: enhancement, fix

#1182 Add scene scraper for (ecchi.)iwara.tv
  SCRAPERS-LIST.md
  scrapers/Iwara.yml
Labels: xPath

#1183 Add scene scraper for oreno3d.com
  SCRAPERS-LIST.md
  scrapers/Oreno3d.yml
Labels: xPath

#1256 Update BelAmi.yml - change to larger image, add tags & studio code
  scrapers/BelAmi.yml
Labels: enhancement, xPath

#1252 Data18 Scene scraper movie title now matches Movie scraper title
  scrapers/data18.yml
Labels: enhancement
