Repository stashapp/CommunityScrapers, pull requests merged in 2023-07, with the labels that each got.

#1320 add gallery and performer scraper to dreamtranny.com
  SCRAPERS-LIST.md
  scrapers/DreamTranny.yml
Labels: enhancement, xPath

#1281 Improve ThisVid scraper
  scrapers/ThisVid.yml
Labels: enhancement, xPath

#1323 Faphouse: Changed the details selector
  scrapers/FapHouse.yml
Labels: fix

#1305 Add scraper for CocksureMen
  SCRAPERS-LIST.md
  scrapers/CocksureMen.yml
Labels: xPath

#1303 Add Noel Alejandro Films scene scraper
  SCRAPERS-LIST.md
  scrapers/NoelAlejandro.yml
Labels: xPath

#1365 Add scene scraping for MetalBondage.com
  SCRAPERS-LIST.md
  scrapers/MetalBondage.yml
Labels: xPath

#1318 Add VRPorn.com
  SCRAPERS-LIST.md
  scrapers/RealJamVR.yml
  scrapers/VRPorn.yml
Labels: xPath
