Repository stashapp/CommunityScrapers, pull requests merged in 2023-04, with the labels that each got.

#1322 Pornhub : Added cookie to bypass age verification prompt
  scrapers/Pornhub.yml
Labels: fix

#1317 Use `availableAt` instead of `createdAt` for date in Arx scraper
  scrapers/Arx.py
  scrapers/Arx.yml
Labels: enhancement

#1314 [Traxxx] add studio Code
  scrapers/Traxxx.yml
  scrapers/traxxx_interface.py
Labels: enhancement, script

#1313 SARJ-LLC minor imporovements
  scrapers/SARJ-LLC.py
  scrapers/SARJ-LLC.yml
Labels: enhancement, script
