Repository stashapp/CommunityScrapers, pull requests merged in 2023-03, with the labels that each got.

#1296 Add director field to DorcelClub scene scraper
  scrapers/DorcelClub.yml
Labels: enhancement

#1302 Update PlayboyPlus.yml
  scrapers/PlayboyPlus.yml
Labels: enhancement, xPath

#1297 Add BoyFun scraper
  SCRAPERS-LIST.md
  scrapers/BoyFun.yml
Labels: xPath

#1289 [KBProductions] Add support for sidechick.com
  SCRAPERS-LIST.md
  scrapers/KBProductions.yml
Labels: enhancement

#1284 Fix Pornbox scraper to return male performers. Add URL to Legalporno scraper
  scrapers/LegalPorno.yml
  scrapers/Pornbox.yml
  scrapers/pornworld.yml
Labels: enhancement, fix
