Repository stashapp/CommunityScrapers, pull requests merged in 2023-02, with the labels that each got.

#1267 add agentredgirl.com to Algolia_Adultime.yml
  SCRAPERS-LIST.md
  scrapers/Algolia.py
  scrapers/Algolia_Adultime.yml
Labels: script

#1266 fix studio scraping for VR Bangers (and network sites)
  scrapers/VRBangers.yml
Labels: xPath, fix

#1264 Update Transerotica.yml
  scrapers/Transerotica.yml
Labels: xPath, fix

#1260 Add more helpful GraphQL 404 errors
  scrapers/py_common/graphql.py
Labels: enhancement, script

#1265 Added momcum.com to AMAMultimedia.yml + map studio names
  SCRAPERS-LIST.md
  scrapers/AMAMultimedia.yml
Labels: enhancement

#1263 Fix Clips4Sale images on scene scraper and search
  scrapers/Clips4Sale.yml
Labels: fix

#1258 Update GoddessSnow.com scraper to have search by name functionality. …
  scrapers/GoddessSnow.yml
Labels: enhancement, xPath

#1233 add more trans500 sites
  SCRAPERS-LIST.md
  scrapers/Trans500.yml
Labels: xPath

#1268 Fix algolia search
  scrapers/Algolia.py
  scrapers/Algolia_Biphoria.yml
Labels: script, fix

#1255 HelixStudios.yml - Scene Scraper - increase image size, add director, add studio code
  scrapers/HelixStudios.yml
Labels: xPath

#1272 fix gallery scraping via algolia
  scrapers/Algolia.py
Labels: script, fix

#1214 add scene scraper for ladyboygold.com and tsraw.com
  SCRAPERS-LIST.md
  scrapers/LadyboyGold.yml
Labels: enhancement

#1275 Improve Xvideos scraper
  scrapers/Xvideos.yml
Labels: enhancement, xPath, fix

#1276 Added DoTheWife.com scene scraper
  SCRAPERS-LIST.md
  scrapers/DoTheWife.yml
Labels: xPath

#1280 Fix Oldje scene performers selector
  scrapers/Oldje.yml
Labels: xPath, fix

#1274 Add ThisVid xPath scene scraper
  SCRAPERS-LIST.md
  scrapers/ThisVid.yml
Labels: xPath

#1271 Create scraper Zishy.yml
  SCRAPERS-LIST.md
  scrapers/Zishy.yml
Labels: xPath

#1270 Added ability to scrape pages behind PlayboyPlus paywall
  scrapers/PlayboyPlus.yml
Labels: enhancement

#1248 Add scraper for Anime-DB
  SCRAPERS-LIST.md
  scrapers/Anime-DB.yml
Labels: xPath, CDP

#1216 Improve Grooby
  SCRAPERS-LIST.md
  scrapers/Algolia_EvilAngel.yml
  scrapers/GroobyNetwork-Brazilian.yml
  scrapers/GroobyNetwork-Partial.yml
Labels: enhancement

#1282 fix VRBangers script for vrbtrans.com
  scrapers/VRBangers.yml
Labels: fix

#1278 Add lordaardvark.com scraper
  SCRAPERS-LIST.md
  scrapers/LordAardvark.yml
Labels: xPath, CDP

#1277 make filthyfamily scraper work with the mobile site
  scrapers/FilthyFamily.yml
Labels: enhancement, xPath, fix
