Repository stashapp/CommunityScrapers, pull requests merged in 2023-05, with the labels that each got.

#1330 Update Hypnotube.yml to add search functionality, fix issue with URL scraping
  scrapers/Hypnotube.yml
Labels: enhancement, fix

#1325 added scraper for visit-x.net
  SCRAPERS-LIST.md
  scrapers/Visit-X.yml
Labels: xPath, CDP

#1321 ManyVids : Added search via sceneByName
  scrapers/ManyVids/ManyVids.py
  scrapers/ManyVids/ManyVids.yml
Labels: enhancement, script
