Repository stashapp/CommunityScrapers, pull requests merged in 2024-08, with the labels that each got.

#1142 Add Python Youtube API Scraper
  SCRAPERS-LIST.md
  scrapers/YouTube.py
  scrapers/YouTube.yml
Labels: script

#1072 Femdom Empire scene search by name
  scrapers/FemdomEmpire.yml
Labels: enhancement, xPath

#1245 Add performer scraper for Babestation TV
  scrapers/BabestationTV.yml
Labels: xPath
